import React, { useEffect, useState } from 'react';
import { ActivityIndicator, Image, Modal, Pressable, ScrollView, Text, View, useWindowDimensions } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import type { Client } from './core/client';
import { routeId } from './core/client';
import { openResponse, shareResponse } from './attachments';
import { Button, ErrorNotice, Label, Row, useAction, useTheme } from './ui';
interface Download { bytes: Uint8Array; mime: string; uri?: string; text?: string }
export function AttachmentView({ client, threadId, messageId, path, name, image, mine }: { client: Client; threadId: string; messageId: string; path: string; name: string; image: boolean; mine: boolean }) {
 const c = useTheme(); const viewport = useWindowDimensions(); const [download,setDownload] = useState<Download>(); const [attempt,setAttempt] = useState(0); const [failed,setFailed] = useState(false); const [preview,setPreview] = useState(false); const action = useAction(); const fg = mine ? '#FFFFFF' : c.text;
 const load = async (signal?: AbortSignal) => {
  const response = await client.response(`/api/threads/${routeId(threadId)}/messages/${routeId(messageId)}/file`, { method: 'POST', signal, headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ path }) });
  const bytes = new Uint8Array(await response.arrayBuffer()); if (bytes.length > 25*1024*1024) throw new Error('File too large to preview.'); const mime = response.headers.get('content-type') ?? '';
  let uri: string | undefined; if (mime.startsWith('image/')) { let binary = ''; for (let i=0;i<bytes.length;i+=8192) binary += String.fromCharCode(...bytes.subarray(i,i+8192)); uri = `data:${mime};base64,${btoa(binary)}`; }
  const text = /^text\/|application\/json/.test(mime) ? new TextDecoder().decode(bytes.slice(0,2*1024*1024)) + (bytes.length>2*1024*1024 ? '\n\n— Preview truncated. Share or open the file to read the rest. —' : '') : undefined;
  return { bytes, mime, uri, text };
 };
 useEffect(() => { if (!image) return; const controller = new AbortController(); setFailed(false); setDownload(undefined); void load(controller.signal).then(d => { if (!controller.signal.aborted) setDownload(d); }).catch(() => { if (!controller.signal.aborted) setFailed(true); }); return () => controller.abort(); },[client,path,threadId,messageId,attempt]);
 const open = () => void action.run(async () => { let d = download; if (!d) { d = await load(); setDownload(d); } if (d.uri || d.text !== undefined) setPreview(true); else await shareResponse(new Response(d.bytes as BodyInit),name); });
 return <><Pressable accessibilityRole="button" accessibilityLabel={`${image ? 'Image' : 'File'} attachment: ${name}. Tap to preview.`} onPress={open} style={{ width: Math.min(300,viewport.width-(mine ? 118 : 106)), maxWidth: '100%', marginBottom: 4, backgroundColor: fg+'1A', borderRadius: 16, overflow: 'hidden' }}>{image ? <><View style={{ width: '100%', aspectRatio: 4/3, justifyContent: 'center', alignItems: 'center' }}>{failed ? <><Label size={13} style={{ color: fg }}>Image unavailable</Label><Button title="Retry" text onPress={() => setAttempt(v => v+1)} /></> : download?.uri ? <Image source={{ uri: download.uri }} onError={() => setFailed(true)} resizeMode="cover" style={{ width: '100%', height: '100%' }} /> : <ActivityIndicator color={fg} />}</View><Label size={13} numberOfLines={1} style={{ color: fg, paddingHorizontal: 10, paddingVertical: 8 }}>{name}</Label></> : <Row style={{ paddingHorizontal: 12, paddingVertical: 10, gap: 10, flexWrap: 'nowrap' }}><Label size={11} bold style={{ color: fg+'AD' }}>FILE</Label><View style={{ flex: 1 }}><Label size={14} numberOfLines={1} style={{ color: fg }}>{name}</Label><Label size={12} style={{ color: fg+'AD' }}>Tap to preview</Label></View></Row>}</Pressable><ErrorNotice error={action.error} />{preview && download && <Modal statusBarTranslucent navigationBarTranslucent onRequestClose={() => setPreview(false)}><SafeAreaView style={{ flex: 1, backgroundColor: c.bg }}><Row style={{ paddingHorizontal: 4, minHeight: 56, gap: 0, flexWrap: 'nowrap', borderBottomWidth: 1, borderColor: c.line }}><Button title="Done" text onPress={() => setPreview(false)} /><Label size={17} bold numberOfLines={1} style={{ flex: 1, textAlign: 'center', paddingHorizontal: 4 }}>{name}</Label><Button title="Share" text onPress={() => void action.run(() => shareResponse(new Response(download.bytes as BodyInit, { headers: { 'Content-Type': download.mime } }),name))} /><Button title="Open" text onPress={() => void action.run(() => openResponse(new Response(download.bytes as BodyInit, { headers: { 'Content-Type': download.mime } }),name))} /></Row><ErrorNotice error={action.error} />{download.uri ? <ScrollView maximumZoomScale={5} minimumZoomScale={1} contentContainerStyle={{ flexGrow: 1, backgroundColor: '#000000' }}><Image source={{ uri: download.uri }} style={{ flex: 1, width: '100%', minHeight: viewport.height-140 }} resizeMode="contain" /></ScrollView> : <ScrollView contentContainerStyle={{ padding: 20 }}><ScrollView horizontal><Text selectable style={{ color: c.text, fontSize: 14, letterSpacing: 0, fontFamily: 'monospace' }}>{download.text}</Text></ScrollView></ScrollView>}</SafeAreaView></Modal>}</>;
}
