import React, { useState } from 'react';
import { isRunningInExpoGo } from 'expo';
import { Platform, View } from 'react-native';
import { Button, Input, Row, SettingRow, ValueRow, Sheet } from './ui';
// Native iOS uses its own compact calendar/time control; web keeps text entry.
const IOSPicker = Platform.OS === 'ios' ? require('@react-native-community/datetimepicker').default as typeof import('@react-native-community/datetimepicker').default : undefined;
export function DateTimeField({ label, value, onChange, timeOnly = false, inline = false }: { label: string; value: Date; onChange: (value: Date) => void; timeOnly?: boolean; inline?: boolean }) {
 const [open, setOpen] = useState(false); const [text, setText] = useState('');
 const show = async () => { if (Platform.OS === 'android') { const { DateTimePickerAndroid } = await import('@react-native-community/datetimepicker'); const time = (date: Date) => DateTimePickerAndroid.open({ value: date, mode: 'time', design: isRunningInExpoGo() ? 'default' : 'material', title: label, onChange: (e, selected) => { if (e.type === 'set' && selected) onChange(selected); } }); if (timeOnly) time(value); else DateTimePickerAndroid.open({ value, mode: 'date', design: isRunningInExpoGo() ? 'default' : 'material', positiveButton: { label: 'Next' }, onChange: (e, selected) => { if (e.type === 'set' && selected) time(selected); } }); } else { setText(timeOnly ? value.toTimeString().slice(0, 5) : `${value.getFullYear()}-${String(value.getMonth()+1).padStart(2,'0')}-${String(value.getDate()).padStart(2,'0')} ${value.toTimeString().slice(0,5)}`); setOpen(true); } };
 if (IOSPicker) return <Row style={{ justifyContent: 'space-between' }}><SettingRow title={label} /><IOSPicker value={value} mode={timeOnly ? 'time' : 'datetime'} display="compact" onChange={(_,date) => { if (date) onChange(date); }} /></Row>;
 const formatted = timeOnly ? `${String(value.getHours()).padStart(2,'0')}:${String(value.getMinutes()).padStart(2,'0')}` : value.toLocaleString([], { month: 'short', day: 'numeric', hour: 'numeric', minute: '2-digit' });
 return <>{inline ? <Button title={formatted} text onPress={() => void show()} /> : <ValueRow title={label} value={formatted} onPress={() => void show()} />}{open && <Sheet centered title={label} onClose={() => setOpen(false)}><View style={{ padding: 24, gap: 12 }}><Input value={text} onChangeText={setText} /><Row><Button title="Cancel" text onPress={() => setOpen(false)} /><Button title="Save" text onPress={() => { const next = new Date(value); if (timeOnly) { const [h,m] = text.split(':').map(Number); next.setHours(h,m,0,0); } else next.setTime(new Date(text.replace(' ', 'T')).getTime()); if (Number.isFinite(next.getTime())) { onChange(next); setOpen(false); } }} /></Row></View></Sheet>}</>;
}
