import React, { useEffect, useRef, useState } from 'react';
import { Linking, Modal, Platform, Pressable, ScrollView, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { CameraView, useCameraPermissions } from 'expo-camera';
import { randomUUID } from 'expo-crypto';
import { fetch as expoFetch } from 'expo/fetch';
import { pair } from './core/client';
import { endpoint, manualInvite, parseInvite, protectedRoute } from './core/pairing';
import type { Connection, Invite } from './core/types';
import { OrbAvatar } from './OrbAvatar';
import { Icon } from './Icon';
import { Button, ErrorNotice, Input, Label, Row, Section, useAction, useTheme } from './ui';

export function Pairing({ onPaired, onCancel, initialLink }: { onPaired: (connection: Connection, token: string) => Promise<void>; onCancel?: () => void; initialLink?: string }) {
 const c = useTheme(); const [address, setAddress] = useState(''); const [code, setCode] = useState(''); const [manual, setManual] = useState(false); const [other, setOther] = useState(false);
 const [invite, setInvite] = useState<Invite>(); const [scanning, setScanning] = useState(false); const [permission, requestPermission] = useCameraPermissions();
 const [scanError, setScanError] = useState<string>();
 const attempt = useRef(randomUUID()); const scanned = useRef(false); const action = useAction();
 const acceptLink = (url: string) => action.run(async () => { setInvite(parseInvite(url)); setManual(false); attempt.current = randomUUID(); setScanning(false); });
 useEffect(() => { if (initialLink) { void acceptLink(initialLink); return; } const sub = Linking.addEventListener('url', e => { if (e.url.startsWith('openmausbot://pair')) void acceptLink(e.url); }); return () => sub.remove(); }, [initialLink]);
 return <><ScrollView keyboardShouldPersistTaps="handled" contentContainerStyle={{ paddingHorizontal: 20, paddingVertical: 24, gap: 24 }}><Row style={{ flexWrap: 'nowrap', gap: 0 }}><Label large bold style={{ flex: 1 }}>Pair with a computer</Label><Button title="Not now" text style={{ minHeight: 48, paddingHorizontal: 12 }} disabled={action.busy} onPress={() => onCancel?.()} /></Row>
 <View style={{ alignItems: 'center' }}><OrbAvatar size={104} color="blue" state={action.busy ? 'loading' : invite ? 'happy' : 'curious'} /></View>
 {invite ? <Section title="Confirm computer"><View style={{ height: 2 }} /><Label size={17} bold>{invite.name}</Label><Row style={{ justifyContent: 'space-between' }}><Label muted>Address</Label><Label style={{ fontFamily: 'monospace' }}>{invite.endpoints[0].url}</Label></Row><Label size={13} muted>{manual ? 'Enter the 6-digit code shown on your desktop:' : protectedRoute(invite.endpoints[0]) ? 'This connection is protected by HTTPS or your Tailscale network.' : 'This connection uses your local network. Only pair with a computer you trust.'}</Label>
 {manual && <Input accessibilityLabel="Pairing code" placeholder="000000" keyboardType="number-pad" value={code} autoCorrect={false} onChangeText={setCode} style={{ fontSize: 24, textAlign: 'center', fontFamily: 'monospace' }} />}
 <Button primary style={{ marginVertical: 4 }} disabled={action.busy || (manual && code.length < 6)} title={action.busy ? 'Connecting…' : manual ? 'Connect' : 'Pair with this computer'} onPress={() => void action.run(async () => { const selected = manual ? manualInvite(address, code) : invite; const result = await pair(selected, Platform.OS === 'ios' ? 'iPhone' : 'Android phone', attempt.current, expoFetch as typeof fetch); await onPaired(result.connection, result.token); })} /><Button title="Choose a different computer" disabled={action.busy} style={{ marginVertical: 4 }} onPress={() => { setInvite(undefined); setCode(''); action.clearError(); }} /></Section> : <>
 <Section title="On your computer"><View style={{ height: 2 }} /><Label>1.  Open OpenMausBot → Settings → Phone</Label><Label>2.  Choose Set up a phone</Label><Button title="Scan QR Code" primary style={{ marginVertical: 4 }} onPress={() => void action.run(async () => { scanned.current = false; setScanError(undefined); setScanning(true); if (!permission?.granted) await requestPermission(); })} /><Label size={13} muted>Scan the QR code, check the computer name, and confirm. The address and one-time credential are filled securely for you.</Label>

 </Section><View style={{ gap: 10 }}><Pressable accessibilityRole="button" accessibilityLabel="Other ways to connect" onPress={() => setOther(!other)} style={{ flexDirection: 'row', alignItems: 'center', padding: 12, minHeight: 48 }}><Label size={14} bold style={{ color: c.accent, flex: 1, lineHeight: 20 }}>Other ways to connect</Label><Icon name={other ? 'up' : 'down'} color={c.accent} /></Pressable>
 {other && <View style={{ gap: 24 }}><Section title="On this network"><View style={{ height: 2 }} /><Label size={13} muted>Scan the computer’s QR code or enter its address below.</Label></Section><Section title="Or enter the address"><View style={{ height: 2 }} /><Input accessibilityLabel="Computer address" placeholder="https://mac.example or 192.168.1.42:8810" autoCapitalize="none" autoCorrect={false} value={address} onChangeText={setAddress} /><Button primary title="Continue" style={{ marginVertical: 4 }} disabled={action.busy || !address.trim()} onPress={() => void action.run(async () => { if (address.includes('://pair') || address.includes('/pair#')) { setInvite(parseInvite(address)); setManual(false); } else { const route = endpoint(address); setInvite({ name: new URL(route.url).hostname, endpoints: [route], credential: '', server: false }); setManual(true); } attempt.current = randomUUID(); })} /><Label size={13} muted>Whatever Phone settings on your computer shows — a secure https:// address, an address on this network, or a Tailscale name like macbook.tail1234.ts.net:8810.</Label></Section></View>}
 </View></>}
 <ErrorNotice error={action.error} /></ScrollView>{scanning && <Modal onRequestClose={() => setScanning(false)}><SafeAreaView style={{ flex: 1, backgroundColor: c.bg }}><View style={{ paddingHorizontal: 8, paddingVertical: 6, justifyContent: 'center' }}><Button title="Cancel" text onPress={() => setScanning(false)} style={{ alignSelf: 'flex-start', minHeight: 48 }} /><Label size={16} bold pointerEvents="none" style={{ position: 'absolute', alignSelf: 'center' }}>Scan QR Code</Label></View>{permission?.granted ? <View style={{ flex: 1 }}><CameraView style={{ flex: 1 }} barcodeScannerSettings={{ barcodeTypes: ['qr'] }} onMountError={e => setScanError(e.message)} onBarcodeScanned={({ data }) => { if (scanned.current) return; scanned.current = true; try { const next = parseInvite(data); setInvite(next); setManual(false); attempt.current = randomUUID(); setScanning(false); } catch (error) { setScanError(error instanceof Error ? error.message : 'This is not an OpenMausBot pairing code.'); setTimeout(() => { scanned.current = false; },800); } }} /><View style={{ position: 'absolute', bottom: 16, left: 16, right: 16, paddingHorizontal: 18, paddingVertical: 14, borderRadius: 18, backgroundColor: c.bg }}><Label style={{ textAlign: 'center', fontWeight: '500', color: scanError ? c.danger : c.text }}>{scanError ?? 'Point the camera at the QR code on your computer'}</Label></View></View> : <View style={{ flex: 1, alignItems: 'center', justifyContent: 'center', padding: 28, gap: 16 }}><Label size={22} bold>{permission?.canAskAgain ? 'Requesting camera access…' : 'Camera access needed'}</Label><Label muted style={{ textAlign: 'center' }}>Allow camera access to scan the pairing QR code shown by OpenMausBot, or go back and enter the address and code by hand.</Label><Button primary title="Open Settings" onPress={() => void Linking.openSettings()} /></View>}</SafeAreaView></Modal>}</>;
}
