import React, { useEffect, useState } from 'react';
import { Modal, Pressable, ScrollView, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import * as ImagePicker from 'expo-image-picker';
import { BOT_AVATAR_CROPS, botAvatarUrlFromStoredPath, type BotAvatarCrop } from '../../shared/bot-avatar';
import type { Session } from './core/session';
import type { Bot, Destination, Instance } from './core/types';
import { canAdminister } from './core/types';
import { routeId } from './core/client';
import { uploadFile } from './attachments';
import { Icon } from './Icon';
import { Avatar } from './Avatar';
import { VoicePreview } from './VoicePreview';
import { Overview } from './Overview';
import { BotPermissions } from './BotPermissions';
import { ActionRow, Button, Choice, ErrorNotice, FormSection, Input, Label, Row, Sheet, Toggle, useAction, useTheme } from './ui';
interface Config { tts?: { configured?: boolean; apiKeyConfigured?: boolean; provider?: string; voice?: string }; imageGen?: { configured?: boolean } }
export function Profile({ session, bot, destination, onBack }: { session: Session; bot: Bot; destination: Destination; onBack: () => void }) {
 const c = useTheme(); const [name, setName] = useState(bot.name); const [title, setTitle] = useState(bot.title); const [description, setDescription] = useState(bot.description); const [notify, setNotify] = useState(bot.notifications); const [crop, setCrop] = useState<BotAvatarCrop>(bot.avatarCrop ?? 'mascot'); const [voice, setVoice] = useState(bot.voice ?? ''); const [speak, setSpeak] = useState(bot.speakReplies ?? false);
 const [instances, setInstances] = useState<Instance[]>([]); const [config, setConfig] = useState<Config>(); const [voices, setVoices] = useState<{ id: string; label: string }[]>([]); const [overview, setOverview] = useState(false); const action = useAction(); const [avatarPrompt, setAvatarPrompt] = useState(''); const admin = canAdminister(session.client.connection);
 const task = bot.tasks?.find(t => t.threadId === destination.threadId); const savedModel = task?.modelSelection ?? bot.modelSelection; const [provider, setProvider] = useState(savedModel.instanceId); const [model, setModel] = useState(savedModel.model); const [effort, setEffort] = useState(savedModel.effort ?? '');
 const patch = async (fields: Record<string, unknown>) => { await session.client.request(`/api/bots/${routeId(bot.id)}/profile`, 'PATCH', fields); await session.refresh(); };
 useEffect(() => { void action.run(async () => { const results = await Promise.allSettled([session.client.instances(), session.client.request<Config>('/api/config'), session.client.request<{ voices: { id: string; label: string }[] }>('/api/tts/voices')]); if (results[0].status === 'fulfilled') setInstances(results[0].value.instances); if (results[1].status === 'fulfilled') setConfig(results[1].value); if (results[2].status === 'fulfilled') setVoices(results[2].value.voices); }); }, []);
 const instance = instances.find(i => i.instanceId === provider); const configured = config?.tts?.configured || config?.tts?.apiKeyConfigured; const engine = config?.tts?.provider ?? 'elevenlabs';
 const [permissions, setPermissions] = useState(false);
 if (permissions) return <BotPermissions key={bot.id} session={session} bot={bot} onBack={() => setPermissions(false)} />;
 return <><Sheet full onClose={onBack}><ScrollView contentContainerStyle={{ paddingBottom: 24, gap: 18 }} keyboardShouldPersistTaps="handled"><View style={{ marginHorizontal: 4, height: 48, justifyContent: 'center' }}><Button title="Done" text onPress={onBack} style={{ alignSelf: 'flex-start', paddingHorizontal: 12 }} /><Label size={17} bold pointerEvents="none" style={{ position: 'absolute', alignSelf: 'center' }}>Bot settings</Label></View><ErrorNotice error={action.error} />
 <FormSection><ActionRow title="What this bot does" icon="info" onPress={() => setOverview(true)} /></FormSection>
 <FormSection><ActionRow title="Permissions" icon="settings" onPress={() => setPermissions(true)} /></FormSection>
 <FormSection title="Model" footer="Provider accounts and API keys stay on your computer. Default sends no reasoning level and lets the provider decide."><Choice label="Provider" value={provider} options={instances.map(i => ({ id: i.instanceId, label: i.displayName }))} onChange={id => { setProvider(id); setModel(instances.find(i => i.instanceId === id)?.models.default ?? ''); }} /><Choice label="Model" value={model} options={instance?.models.options.map(m => ({ id: m.id, label: m.label ?? m.id })) ?? [{ id: model, label: model }]} onChange={setModel} /><Choice label="Reasoning effort" value={effort} options={[{ id: '', label: 'Default' }, ...(instance?.capabilities?.effortLevels ?? []).map(id => ({ id, label: id.slice(0, 1).toUpperCase() + id.slice(1) }))]} onChange={setEffort} /><ActionRow title="Apply model" icon="check" disabled={action.busy || !admin || task?.busy || (model === savedModel.model && provider === savedModel.instanceId && effort === (savedModel.effort ?? ''))} onPress={() => void action.run(async () => { await session.client.task(destination, 'PATCH', { modelSelection: { instanceId: provider, model, ...(effort ? { effort } : {}) }, requireAvailableModel: true }); await session.refresh(); })} /></FormSection>
 <FormSection title="Avatar" footer="PNG, JPEG, GIF, or WebP, up to 10 MB. Images are stored on your paired computer and loaded with this phone's pairing token."><View style={{ alignItems: 'center', paddingVertical: 4 }}><Avatar bot={{ ...bot, avatarCrop: crop }} client={session.client} size={112} happy /></View><Row style={{ gap: 0, height: 48, flexWrap: 'nowrap' }}>{BOT_AVATAR_CROPS.map((v, i) => <Pressable key={v} onPress={() => setCrop(v)} style={{ flex: 1, height: 40, flexDirection: 'row', gap: 6, alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: c.outline, marginLeft: i ? -1 : 0, borderTopLeftRadius: i === 0 ? 20 : 0, borderBottomLeftRadius: i === 0 ? 20 : 0, borderTopRightRadius: i === 3 ? 20 : 0, borderBottomRightRadius: i === 3 ? 20 : 0, backgroundColor: v === crop ? c.tint : 'transparent' }}>{v === crop && <Icon name="check" size={18} color={c.text} />}<Label size={14} style={{ lineHeight: 20, letterSpacing: 0.1 }}>{v.slice(0, 1).toUpperCase() + v.slice(1)}</Label></Pressable>)}</Row><ActionRow title="Upload image" icon="add" disabled={action.busy || !admin} onPress={() => void action.run(async () => { const result = await ImagePicker.launchImageLibraryAsync({ mediaTypes: ['images'], quality: 1 }); if (result.canceled) return; const item = result.assets[0]; const saved = await uploadFile(session.client, item.uri, item.fileName ?? 'avatar.jpg', item.mimeType ?? 'image/jpeg'); const url = botAvatarUrlFromStoredPath(saved.path); if (!url) throw new Error('Choose a PNG, JPEG, GIF or WebP image.'); const nextCrop = crop === 'mascot' ? 'circle' : crop; await patch({ avatarUrl: url, avatarCrop: nextCrop }); setCrop(nextCrop); })} />{bot.avatarUrl && <ActionRow title="Use mascot" icon="delete" danger disabled={action.busy || !admin} onPress={() => void action.run(async () => { await patch({ avatarUrl: null, avatarCrop: 'mascot' }); setCrop('mascot'); })} />}</FormSection>
 <FormSection title="Generate an avatar" footer="To generate images, configure the shared image provider in OpenMausBot on your computer. Provider keys cannot be added from a phone."><Input label="Art direction" value={avatarPrompt} onChangeText={setAvatarPrompt} maxLength={400} multiline style={{ minHeight: 86 }} /><ActionRow title="Generate on computer" icon="photo" disabled={action.busy || !admin || !avatarPrompt.trim() || !config?.imageGen?.configured} onPress={() => void action.run(async () => { await session.client.response(`/api/bots/${routeId(bot.id)}/avatar/generate`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ prompt: avatarPrompt.trim() }) }, 150_000); await session.refresh(); })} /></FormSection>
 <FormSection title="Identity"><Input label="Name" value={name} onChangeText={setName} /><Input label="Title" value={title} onChangeText={setTitle} /><Input label="What this agent does" value={description} onChangeText={setDescription} multiline style={{ minHeight: 104 }} /><Row><Label style={{ flex: 1 }}>Agent notifications</Label><Toggle label="Agent notifications" value={notify} onChange={setNotify} /></Row></FormSection>
 <FormSection title="Voice"><Choice label="Voice engine" value={engine} options={[{ id: 'elevenlabs', label: 'ElevenLabs' }, { id: 'fish', label: 'Fish Audio' }, { id: 'chatterbox', label: 'Chatterbox' }, { id: 'system', label: 'Built-in' }]} disabled={action.busy || !admin} onChange={next => void action.run(async () => { setConfig(await session.client.request<Config>('/api/config', 'PUT', { tts: { provider: next } })); setVoices((await session.client.request<{ voices: { id: string; label: string }[] }>('/api/tts/voices')).voices); setVoice(''); })} />{configured ? <><Choice label="Voice" value={voice} options={[{ id: '', label: 'Workspace default' }, ...voices]} onChange={setVoice} /><Row><Label style={{ flex: 1 }}>Speak replies</Label><Toggle label="Speak replies" value={speak} onChange={setSpeak} /></Row><VoicePreview client={session.client} name={name} voice={voice} /></> : <><Row style={{ gap: 10 }}><Icon name="volumeOff" size={18} color={c.muted} /><Label size={13} muted>{engine === 'elevenlabs' ? 'ElevenLabs' : engine} is not configured</Label></Row><Label size={13} muted>Add the shared ElevenLabs key in this agent's profile on the computer. The key is never returned to this phone.</Label></>}</FormSection>
 <FormSection><ActionRow title="Save profile changes" disabled={action.busy || !name.trim() || !admin} onPress={() => void action.run(() => patch({ name: name.trim(), title, description, notifications: notify, avatarCrop: crop, voice, speakReplies: speak }))} /></FormSection>
 </ScrollView></Sheet>{overview && <Modal animationType="slide" onRequestClose={() => setOverview(false)}><SafeAreaView style={{ flex: 1, backgroundColor: c.bg }}><Overview session={session} botId={bot.id} name={bot.name} onBack={() => setOverview(false)} /></SafeAreaView></Modal>}</>;
}
