import React, { useState } from 'react';
import { Pressable, ScrollView, View } from 'react-native';
import { randomUUID } from 'expo-crypto';
import { Button, DialogBody, Input, Label, Row, Sheet, useTheme } from './ui';
export interface QuickReply { id: string; title: string; prompt: string; icon: string }
export const defaultReplies: QuickReply[] = [{ id: 'default.diff', title: 'Show diff', prompt: 'Show latest git diff', icon: 'diff' }, { id: 'default.tests', title: 'Run tests', prompt: 'Run all automated tests', icon: 'tests' }, { id: 'default.explain', title: 'Explain steps', prompt: 'Explain the changes in detail', icon: 'explain' }, { id: 'default.next', title: "What's next?", prompt: 'What should we do next?', icon: 'next' }];
export const replyGlyphs: Record<string,string> = { next: '→', diff: '±', tests: '✓', explain: '?', build: '⌘', bug: '!', document: '▤', terminal: '>_', send: '➤', search: '⌕', history: '↶', list: '☷' };
export function QuickReplies({ replies, onChange, onClose }: { replies: QuickReply[]; onChange: (r: QuickReply[]) => void; onClose: () => void }) {
 const c = useTheme(); const [editing, setEditing] = useState<QuickReply>(); const [resetting, setResetting] = useState(false); const move = (i: number, delta: number) => { const next = [...replies]; const [item] = next.splice(i,1); next.splice(i+delta,0,item); onChange(next); };
 return <><Sheet centered title="Quick replies" onClose={onClose}><ScrollView style={{ maxHeight: 500 }} contentContainerStyle={{ paddingHorizontal: 24, paddingTop: 16, gap: 8 }}><Label size={13} muted style={{ lineHeight: 20 }}>{replies.length ? 'Edit, reorder, or remove the prompts shown above an empty composer.' : 'The chip row is hidden while this list is empty.'}</Label>{replies.map((r,i) => <View key={r.id}><Row style={{ flexWrap: 'nowrap', minHeight: 48 }}><View style={{ flex: 1 }}><Label size={14} numberOfLines={1} style={{ lineHeight: 20, fontWeight: '500' }}>{r.title}</Label><Label size={12} muted numberOfLines={1} style={{ lineHeight: 20 }}>{r.prompt}</Label></View><Button title="Edit" text style={{ paddingHorizontal: 12, minHeight: 48 }} onPress={() => setEditing(r)} /></Row><Row style={{ gap: 2, flexWrap: 'nowrap' }}><Button title="Move up" text disabled={i === 0} style={{ paddingHorizontal: 12, minHeight: 48 }} onPress={() => move(i,-1)} /><Button title="Move down" text disabled={i === replies.length-1} style={{ paddingHorizontal: 12, minHeight: 48 }} onPress={() => move(i,1)} /><Button title="Remove" text style={{ paddingHorizontal: 12, minHeight: 48 }} onPress={() => onChange(replies.filter(x => x.id !== r.id))} /></Row><View style={{ height: 1, backgroundColor: c.line }} /></View>)}</ScrollView><Row style={{ justifyContent: 'flex-end', paddingHorizontal: 24, paddingTop: 24, gap: 4 }}><Button title="Add" text style={{ paddingHorizontal: 12, minHeight: 48 }} onPress={() => setEditing({ id: randomUUID(), title: '', prompt: '', icon: 'next' })} /><Button title="Reset" text danger style={{ paddingHorizontal: 12, minHeight: 48 }} onPress={() => setResetting(true)} /><Button title="Done" text style={{ paddingHorizontal: 12, minHeight: 48 }} onPress={onClose} /></Row></Sheet>
 {resetting && <Sheet centered title="Reset quick replies?" onClose={() => setResetting(false)}><DialogBody actions={<><Button title="Cancel" text onPress={() => setResetting(false)} /><Button title="Reset" text danger onPress={() => { onChange(defaultReplies); setResetting(false); }} /></>}><Label muted>This restores the four chips the app came with and discards your own.</Label></DialogBody></Sheet>}
 {editing && <Sheet centered title={replies.some(r => r.id === editing.id) ? 'Edit quick reply' : 'New quick reply'} onClose={() => setEditing(undefined)}><DialogBody gap={12} actions={<><Button title="Cancel" text onPress={() => setEditing(undefined)} /><Button title="Save" text disabled={!editing.title.trim() || !editing.prompt.trim()} onPress={() => { const next = { ...editing, title: editing.title.trim(), prompt: editing.prompt.trim() }; onChange(replies.some(r => r.id === next.id) ? replies.map(r => r.id === next.id ? next : r) : [...replies,next]); setEditing(undefined); }} /></>}><Input label="Label" value={editing.title} onChangeText={title => setEditing({ ...editing, title })} /><Input label="Prompt" value={editing.prompt} onChangeText={prompt => setEditing({ ...editing, prompt })} multiline style={{ minHeight: 86 }} /><Label size={13} muted>Icon</Label><ScrollView horizontal contentContainerStyle={{ gap: 6 }}>{Object.entries(replyGlyphs).map(([id,glyph]) => <Pressable key={id} accessibilityLabel={id} onPress={() => setEditing({ ...editing, icon: id })} style={{ borderWidth: 1, borderColor: c.line, borderRadius: 8, paddingHorizontal: 12, paddingVertical: 6, backgroundColor: editing.icon === id ? c.tint : 'transparent' }}><Label size={13}>{glyph}</Label></Pressable>)}</ScrollView></DialogBody></Sheet>}</>;
}
