import React, { useEffect, useState } from 'react';
import { Pressable, RefreshControl, ScrollView, View } from 'react-native';
import type { Routine, RoutineInput, RoutineRun, RoutineSchedule } from '../../shared/routines';
import type { Session } from './core/session';
import type { Destination } from './core/types';
import { routeId } from './core/client';
import { canAdminister } from './core/types';
import { Avatar } from './Avatar';
import { Icon } from './Icon';
import { Menu } from './Menu';
import { DateTimeField } from './DateTimeField';
import { ActionRow, Button, Choice, DialogBody, ErrorNotice, FormSection, Header, IconButton, Input, Label, RadioRow, Row, ValueRow, Sheet, useAction, useTheme } from './ui';

const days = ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'];
const dateStamp = (at: number) => new Date(at).toLocaleString([], { month: 'short', day: 'numeric', year: 'numeric', hour: 'numeric', minute: '2-digit' });
const scheduleText = (s: RoutineSchedule) => s.type === 'interval' ? `Every ${s.everyMinutes} minutes · starting ${dateStamp(s.anchorAt)}` : s.type === 'once' ? dateStamp(s.at) : s.type === 'daily' ? `${s.weekdays?.length === 7 ? 'Every day' : s.weekdays?.join(',') === '1,2,3,4,5' ? 'Weekdays' : s.weekdays?.map(i => days[i].slice(0,3)).join(', ')} at ${s.time}` : 'Custom schedule';
function RoutineEditor({ session, routine, onSaved, onCancel }: { session: Session; routine?: Routine; onSaved: () => Promise<void>; onCancel: () => void }) {
 const c = useTheme(); const schedule = routine?.schedule; const action = useAction();
 const [name, setName] = useState(routine?.name ?? ''); const [prompt, setPrompt] = useState(routine?.prompt ?? ''); const [botId, setBotId] = useState(routine?.botId ?? session.state.bots.find(b => !b.hidden)?.id ?? ''); const [runOn, setRunOn] = useState(routine?.runOn ?? 'maus'); const [kind, setKind] = useState<RoutineSchedule['type']>(schedule?.type ?? 'daily');
 const [minutes, setMinutes] = useState(schedule?.type === 'interval' ? String(schedule.everyMinutes) : '15'); const [date, setDate] = useState(new Date(schedule?.type === 'once' ? schedule.at : schedule?.type === 'interval' ? schedule.anchorAt : Date.now() + 3_600_000)); const [time, setTime] = useState(() => { const d = new Date(); d.setHours(9,0,0,0); if (schedule?.type === 'daily') { const [h,m] = schedule.time.split(':').map(Number); d.setHours(h,m,0,0); } return d; });
 const [weekdays, setWeekdays] = useState<number[]>(schedule?.type === 'daily' || schedule?.type === 'interval' ? schedule.weekdays ?? [1,2,3,4,5] : [1,2,3,4,5]); const [timeout, setTimeoutMinutes] = useState(routine?.timeoutMinutes ? String(routine.timeoutMinutes) : ''); const [advanced, setAdvanced] = useState(false); const [custom, setCustom] = useState(false); const [intervalMenu, setIntervalMenu] = useState<{ x: number; y: number }>(); const [cloud, setCloud] = useState(false);
 useEffect(() => { void Promise.all([session.client.request<{ box?: { configured?: boolean } }>('/api/config'), session.client.instances()]).then(([config, instances]) => setCloud(!!config.box?.configured && instances.instances.some(i => i.instanceId === 'box' && i.snapshot?.state === 'ready'))).catch(() => {}); }, []);
 const save = () => action.run(async () => { let next: RoutineSchedule; if (kind === 'once') next = { type: kind, at: date.getTime() }; else if (kind === 'daily') { if (!weekdays.length) throw new Error('Choose at least one day.'); next = { type: kind, time: `${String(time.getHours()).padStart(2,'0')}:${String(time.getMinutes()).padStart(2,'0')}`, weekdays }; } else if (kind === 'interval') { if (!Number.isInteger(+minutes) || +minutes < 5 || +minutes > 1440) throw new Error('Choose an interval from 5 minutes to 24 hours.'); next = { type: kind, everyMinutes: +minutes, anchorAt: date.getTime(), ...(schedule?.type === 'interval' ? { weekdays: schedule.weekdays, window: schedule.window, endsAt: schedule.endsAt } : {}) }; } else { if (!schedule || schedule.type !== 'cron') throw new Error('Choose a supported schedule.'); next = schedule; }
 const input: RoutineInput = { name: name.trim().slice(0,80), prompt: prompt.trim().slice(0,20000), botId, target: routine?.target ?? 'bot', groupId: routine?.groupId ?? null, runOn, schedule: next, timeoutMinutes: timeout ? +timeout : null, overlap: routine?.overlap ?? 'skip' }; await session.client.request(routine ? `/api/routines/${routeId(routine.id)}` : '/api/routines', routine ? 'PATCH' : 'POST', input); await onSaved(); });
 return <Sheet full onClose={onCancel}><ScrollView keyboardShouldPersistTaps="handled" contentContainerStyle={{ gap: 18, paddingBottom: 24 }}><Row style={{ paddingHorizontal: 4, justifyContent: 'space-between', minHeight: 48, flexWrap: 'nowrap' }}><Button title="Cancel" text style={{ paddingHorizontal: 12 }} onPress={onCancel} /><Label size={17} bold style={{ position: 'absolute', left: 80, right: 80, textAlign: 'center' }}>{routine ? 'Edit routine' : 'New routine'}</Label><Button title="Save" text style={{ paddingHorizontal: 12 }} disabled={action.busy || !name.trim() || !prompt.trim() || !botId} onPress={() => void save()} /></Row><ErrorNotice error={action.error} />
 <FormSection title="Work"><Input label="Routine name" value={name} onChangeText={setName} maxLength={80} /><Choice label="Agent" value={botId} options={session.state.bots.filter(b => !b.hidden).map(b => ({ id: b.id, label: b.name }))} onChange={setBotId} /><Input label="What should the agent do?" value={prompt} onChangeText={setPrompt} multiline style={{ minHeight: 128 }} /></FormSection>
 <FormSection title="Where does it run?" footer={runOn === 'maus' ? "Uses this agent's selected model and computer setting on the paired computer." : 'Runs the agent and its tools inside its Box virtual machine. The VM wakes automatically for each run; keep OpenMausBot running so its scheduler can launch the job.'}><RadioRow title="This computer" icon="computer" selected={runOn === 'maus'} onPress={() => setRunOn('maus')} /><RadioRow title="Cloud VM" icon="computer" selected={runOn === 'cloud'} disabled={!cloud && runOn !== 'cloud'} onPress={() => setRunOn('cloud')} /></FormSection>
 <FormSection title="Schedule" footer={kind === 'interval' ? 'Each occurrence starts with fresh context. Results collect in one thread, and full run logs remain available. If the previous run is still active, the next occurrence is skipped instead of queued.' : 'Each occurrence starts with fresh context. Results collect in one thread, and full run logs remain available. No cron syntax is used.'}>{kind === 'cron' && <RadioRow title="Newer schedule" selected disabled onPress={() => {}} />}<RadioRow title="One time" selected={kind === 'once'} onPress={() => setKind('once')} /><RadioRow title="Selected days" selected={kind === 'daily'} onPress={() => setKind('daily')} /><RadioRow title="Every X minutes" selected={kind === 'interval'} onPress={() => { setKind('interval'); if (!routine && !timeout) setTimeoutMinutes('30'); }} />
 {kind === 'once' && <DateTimeField label="Run" value={date} onChange={setDate} />}{kind === 'daily' && <><DateTimeField label="Time" value={time} onChange={setTime} timeOnly /><Row style={{ gap: 4 }}>{days.map((day,i) => <Pressable key={day} accessibilityRole="checkbox" accessibilityLabel={day} accessibilityState={{ checked: weekdays.includes(i) }} onPress={() => setWeekdays(v => v.includes(i) ? v.filter(d => d !== i) : [...v, i].sort())} style={{ width: 48, height: 48, borderRadius: 24, backgroundColor: weekdays.includes(i) ? c.accent : c.dark ? '#36343B' : '#E7E0EC', alignItems: 'center', justifyContent: 'center' }}><Label size={14} style={{ color: weekdays.includes(i) ? '#FFFFFF' : c.text }}>{day[0]}</Label></Pressable>)}</Row></>}
 {kind === 'interval' && <><Row style={{ gap: 2 }}><Label size={16}>Runs every</Label><Pressable accessibilityRole="button" accessibilityLabel="Repeat interval" onPress={e => setIntervalMenu({ x: e.nativeEvent.pageX, y: e.nativeEvent.pageY })} style={{ minHeight: 48, paddingHorizontal: 12, flexDirection: 'row', alignItems: 'center' }}><Label size={16} style={{ color: c.accent }}>{custom ? 'Custom' : minutes}</Label><Icon name="dropdown" color={c.accent} /></Pressable><Label size={16}>minutes, starting</Label><DateTimeField label="Starting" value={date} onChange={setDate} inline /><Label size={16}>.</Label></Row>{custom && <Input label="Custom interval" value={minutes} onChangeText={setMinutes} keyboardType="number-pad" />}{intervalMenu && <Menu {...intervalMenu} width={160} onClose={() => setIntervalMenu(undefined)}>{['5','10','15','30','60','Custom'].map(v => <Pressable key={v} onPress={() => { setCustom(v === 'Custom'); setMinutes(v === 'Custom' ? '' : v); setIntervalMenu(undefined); }} style={{ minHeight: 48, paddingHorizontal: 16, justifyContent: 'center' }}><Label size={16}>{v}</Label></Pressable>)}</Menu>}</>}

 </FormSection><FormSection footer={advanced ? 'Optional. This only stops a stuck run; it does not control how often the routine starts.' : undefined}><ValueRow title="Advanced" value={advanced ? 'Hide' : timeout ? `${timeout} min limit` : 'No limit'} onPress={() => setAdvanced(!advanced)} />{advanced && <Choice label="Time limit" value={timeout} options={[{ id: '', label: 'No limit' }, ...Array.from({ length: 48 }, (_,i) => ({ id: String((i+1)*5), label: `${(i+1)*5} minutes` }))]} onChange={setTimeoutMinutes} />}</FormSection>
 </ScrollView></Sheet>;
}
export function Routines({ session, onBack, onOpen }: { session: Session; onBack: () => void; onOpen: (destination: Destination) => void }) {
 const c = useTheme(); const [routines, setRoutines] = useState<Routine[]>([]); const [runs, setRuns] = useState<RoutineRun[]>([]); const [editor, setEditor] = useState<Routine | 'new'>(); const [menu, setMenu] = useState<Routine & { anchor: { x: number; y: number } }>(); const [deleting, setDeleting] = useState<Routine>(); const [expanded, setExpanded] = useState<string[]>([]); const action = useAction(); const admin = canAdminister(session.client.connection);
 const load = async () => { const data = await session.client.request<{ routines: Routine[]; runs: RoutineRun[] }>('/api/routines'); setRoutines(data.routines); setRuns(data.runs ?? []); }; useEffect(() => { void action.run(load); const timer = setInterval(() => void action.run(load),10_000); return () => clearInterval(timer); }, []);
 return <View style={{ flex: 1 }}><Header title="Threads & Routines" onBack={onBack} trailing={<IconButton icon="add" label="New routine" size={36} glyph={18} disabled={!admin} onPress={() => setEditor('new')} />} /><ScrollView refreshControl={<RefreshControl refreshing={action.busy} onRefresh={() => void action.run(load)} />} contentContainerStyle={{ paddingTop: 16, paddingBottom: 32, gap: 18 }}><ErrorNotice error={action.error} /><FormSection footer="No cron syntax. Every run uses the agent's existing model, tools, permissions, computer, and connected apps. Times follow the paired computer's local timezone."><Row style={{ gap: 10 }}><Icon name="chat" size={18} color={c.text} /><Label size={13}>Thread = one conversation and result</Label></Row><Row style={{ gap: 10, flexWrap: 'nowrap' }}><Icon name="schedule" size={18} color={c.text} /><Label size={13} style={{ flex: 1 }}>Routine = scheduled work with one results thread</Label></Row></FormSection>
 <View style={{ paddingHorizontal: 20, gap: 10 }}><Label size={12} bold muted>ROUTINES</Label><View style={{ height: 1, backgroundColor: c.line }} /></View>{!routines.length && <View style={{ alignItems: 'center', gap: 4, paddingVertical: 14 }}><Label size={16} bold>No routines</Label><Label size={13} muted>Schedule recurring or one-time agent work.</Label></View>}
 {routines.slice().sort((a,b) => (a.nextRunAt ?? Infinity)-(b.nextRunAt ?? Infinity)).map(r => { const bot = session.state.bots.find(b => b.id === r.botId); return <Pressable key={r.id} onPress={() => setEditor(r)} style={{ flexDirection: 'row', alignItems: 'center', paddingHorizontal: 20, paddingVertical: 8, gap: 12 }}>{bot && <Avatar bot={bot} client={session.client} size={42} />}<View style={{ flex: 1, gap: 3 }}><Label size={16} bold>{r.name}</Label><Label size={12} muted numberOfLines={2}>{bot?.name ?? 'Deleted agent'} · {scheduleText(r.schedule)} · {r.runOn === 'cloud' ? 'Cloud VM' : 'This computer'}</Label></View>{!r.enabled && <Label size={12} muted>Paused</Label>}<Pressable accessibilityRole="button" accessibilityLabel={`Actions for ${r.name}`} style={{ width: 48, height: 48, justifyContent: 'center', alignItems: 'center' }} onPress={e => setMenu({ ...r, anchor: { x: e.nativeEvent.pageX - 96, y: e.nativeEvent.pageY + 38 } })}><View style={{ width: 36, height: 36, borderRadius: 18, backgroundColor: c.chrome, alignItems: 'center', justifyContent: 'center' }}><Icon name="more" size={18} color={c.text} /></View></Pressable></Pressable>; })}
 <View style={{ paddingHorizontal: 20, gap: 10 }}><Label size={12} bold muted>RUN RECEIPTS</Label><View style={{ height: 1, backgroundColor: c.line }} /></View>{!runs.length && <Label size={14} muted style={{ paddingHorizontal: 20 }}>Completed, waiting, failed, and manually started runs appear here.</Label>}{runs.slice().sort((a,b) => b.scheduledFor-a.scheduledFor).slice(0,50).map(run => <View key={run.id}><Pressable onPress={() => setExpanded(v => v.includes(run.id) ? v.filter(id => id !== run.id) : [...v,run.id])} style={{ flexDirection: 'row', alignItems: 'center', paddingHorizontal: 20, paddingVertical: 8, gap: 12 }}><Icon name={run.status === 'completed' ? 'checkCircle' : 'schedule'} size={20} color={run.status === 'failed' ? c.danger : c.accent} /><View style={{ flex: 1, gap: 2 }}><Label>{run.routineName}</Label><Label size={12} muted>{session.state.bots.find(b => b.id === run.botId)?.name} · {dateStamp(run.scheduledFor)}</Label></View><Label size={12} style={{ color: run.status === 'failed' || run.status === 'missed' ? c.danger : c.accent }}>{run.status === 'waiting' ? 'Needs you' : run.status[0].toUpperCase() + run.status.slice(1)}</Label><Icon name={expanded.includes(run.id) ? 'up' : 'down'} size={20} color={c.muted} /></Pressable>{expanded.includes(run.id) && <View style={{ paddingLeft: 52, paddingRight: 20, paddingBottom: 10, gap: 8 }}>{!!run.output && <Label size={14} selectable>{run.output}</Label>}{!!run.error && <ErrorNotice error={run.error} />}{run.status === 'waiting' && <Label size={14}>This thread is waiting for your answer.</Label>}{(run.threadId || run.executionThreadId || run.resultsThreadId) && <ActionRow title="Open thread" icon="share" onPress={() => onOpen({ kind: run.target === 'room-goal' ? 'groups' : 'bots', id: run.target === 'room-goal' ? run.groupId! : run.botId, threadId: (run.executionThreadId ?? run.threadId ?? run.resultsThreadId)! })} />}</View>}</View>)}
 <FormSection title="Webhooks" footer="Creating or rotating a webhook changes an internet-reachable trigger and signing secret, so webhook management remains on the paired computer. Webhook run receipts still appear above."><Row style={{ gap: 10 }}><Icon name="lock" size={18} color={c.muted} /><Label size={13} muted>Computer only</Label></Row></FormSection></ScrollView>
 {editor && <RoutineEditor key={editor === 'new' ? 'new' : editor.id} session={session} routine={editor === 'new' ? undefined : editor} onCancel={() => setEditor(undefined)} onSaved={async () => { await load(); setEditor(undefined); }} />}{menu && <Menu {...menu.anchor} width={112} onClose={() => setMenu(undefined)}><View style={{ paddingHorizontal: 12 }}><ActionRow title="Run now" color={c.text} fontSize={16} onPress={() => void action.run(async () => { await session.client.request(`/api/routines/${routeId(menu.id)}/run`,'POST',{}); setMenu(undefined); await load(); })} /><ActionRow color={c.text} fontSize={16} title={menu.enabled ? 'Pause' : 'Resume'} onPress={() => void action.run(async () => { await session.client.request(`/api/routines/${routeId(menu.id)}`,'PATCH',{ enabled: !menu.enabled }); setMenu(undefined); await load(); })} /><ActionRow color={c.text} fontSize={16} title="Edit" onPress={() => { setEditor(menu); setMenu(undefined); }} /><ActionRow color={c.text} fontSize={16} title="Delete" danger onPress={() => { setDeleting(menu); setMenu(undefined); }} /></View></Menu>}
 {deleting && <Sheet centered title={`Delete ${deleting.name}?`} onClose={() => setDeleting(undefined)}><DialogBody actions={<><Button title="Cancel" text onPress={() => setDeleting(undefined)} /><Button title="Delete routine" text danger disabled={action.busy} onPress={() => void action.run(async () => { await session.client.request(`/api/routines/${routeId(deleting.id)}`,'DELETE'); setDeleting(undefined); await load(); })} /></>}><Label muted>Past run receipts remain available.</Label><ErrorNotice error={action.error} /></DialogBody></Sheet>}
 </View>;
}
