import React, { useState } from 'react';
import { Pressable, ScrollView, View } from 'react-native';
import type { Session } from './core/session';
import type { State } from './core/store';
import type { Destination, Task } from './core/types';
import { ThreadRow } from './ThreadRow';
import { threadGroups } from './core/threads';
import { Avatar } from './Avatar';
import { Button, DialogBody, ErrorNotice, IconButton, Input, Label, Row, Sheet, useAction, useTheme } from './ui';

export function Threads({ session, state, destination, onSelect, onBack }: { session: Session; state: State; destination: Destination; onSelect: (d: Destination) => void; onBack: () => void }) {
 const [deleting, setDeleting] = useState<(typeof tasks)[number]>(); const [editing, setEditing] = useState<string>(); const [newTitle, setNewTitle] = useState(''); const action = useAction(); const c = useTheme();
 const owner = destination.kind === 'bots' ? state.bots.find(b => b.id === destination.id) : state.groups.find(g => g.id === destination.id);
 const bot = destination.kind === 'bots' ? state.bots.find(b => b.id === destination.id) : undefined;
 const tasks: Task[] = (bot ? threadGroups(bot,destination.threadId,'',true,Object.keys(state.queues).filter(k => state.queues[k]?.length)).flatMap(g => g.tasks) : owner?.tasks ?? []).filter(t => !('routineRunId' in t && t.routineRunId)).slice().sort((a,b) => Number(!!('archivedAt' in a && a.archivedAt)) - Number(!!('archivedAt' in b && b.archivedAt)));
 const select = (threadId: string) => action.run(async () => { const d = { ...destination, threadId }; if (d.kind === 'groups' && owner?.threadId !== threadId) { await session.client.task(d, 'POST'); await session.refresh(); } onSelect(d); });
 return <><Sheet centered tonal title={`${owner?.name}'s threads`} onClose={onBack} action={<IconButton icon="add" label="New thread" chrome={false} disabled={action.busy} onPress={() => void action.run(async () => { const result = await session.client.createTask(destination, ''); await session.refresh(); const created = result.bot ?? result.group; if (created) onSelect({ ...destination, threadId: created.threadId }); })} />}>
 <Row style={{ paddingHorizontal: 20, paddingVertical: 8, gap: 12 }}>{bot && <Avatar bot={bot} client={session.client} size={48} />}<View style={{ gap: 2 }}><Label size={16} bold>{owner?.name}</Label><Label size={14} muted>{bot ? 'Agent threads' : 'Group threads'}</Label></View></Row><Label size={13} muted style={{ marginHorizontal: 20, paddingVertical: 2, letterSpacing: 0 }}>A thread is one conversation and result. Each routine keeps its results in one thread.</Label>
 <ScrollView style={{ maxHeight: 360 }} contentContainerStyle={{ paddingHorizontal: 20 }}><ErrorNotice error={action.error} />{tasks.map((t,index) => <React.Fragment key={t.threadId}>{t.archivedAt != null && (index === 0 || tasks[index-1].archivedAt == null) ? <Label size={13} bold muted style={{ paddingVertical: 8 }}>Archived</Label> : bot?.projects?.find(p => p.id === t.projectId) && (index === 0 || tasks[index-1].projectId !== t.projectId) ? <Label muted style={{ paddingVertical: 8 }}>{bot.projects.find(p => p.id === t.projectId)?.emoji || '📁'} {bot.projects.find(p => p.id === t.projectId)?.name}</Label> : null}<View style={{ flexDirection: 'row', gap: 8, alignItems: 'center', paddingVertical: 10 }}><Pressable accessibilityRole="button" disabled={t.threadId === destination.threadId} onPress={() => void select(t.threadId)} style={{ flex: 1, gap: 5 }}><ThreadRow task={t} selected={t.threadId === destination.threadId} queued={!!state.queues[t.threadId]?.length} /></Pressable>
 {bot && <Pressable accessibilityLabel={`${'archivedAt' in t && t.archivedAt ? 'Unarchive' : 'Archive'} ${t.title}`} onPress={() => void action.run(async () => { await session.client.task({ ...destination, threadId: t.threadId }, 'PATCH', { archivedAt: 'archivedAt' in t && t.archivedAt ? null : Date.now() }); await session.refresh(); })} style={{ paddingHorizontal: 8 }}><Label size={12} muted style={{ fontWeight: '500' }}>{'archivedAt' in t && t.archivedAt ? 'Unarchive' : 'Archive'}</Label></Pressable>}<IconButton icon="edit" color={c.muted} label={`Rename ${t.title}`} chrome={false} onPress={() => { setEditing(t.threadId); setNewTitle(t.title); }} /><IconButton icon="delete" label={`Delete ${t.title}`} chrome={false} color={c.danger} disabled={!!('busy' in t && t.busy) || tasks.length <= 1} onPress={() => setDeleting(t)} /></View></React.Fragment>)}</ScrollView><Button title="Done" text style={{ alignSelf: 'flex-end', marginRight: 12, minHeight: 48 }} onPress={onBack} />
 </Sheet>{deleting && <Sheet centered title={`Delete ${deleting.title || 'Untitled thread'}?`} onClose={() => setDeleting(undefined)}><DialogBody actions={<><Button title="Cancel" text onPress={() => setDeleting(undefined)} /><Button title="Delete" text danger disabled={action.busy} onPress={() => void action.run(async () => { await session.client.task({ ...destination, threadId: deleting.threadId }, 'DELETE'); await session.refresh(); setDeleting(undefined); if (deleting.threadId === destination.threadId) { const next = destination.kind === 'bots' ? session.snapshot().bots.find(b => b.id === destination.id) : session.snapshot().groups.find(g => g.id === destination.id); if (next) onSelect({ ...destination, threadId: next.threadId }); } })} /></>}><Label muted>This conversation will be deleted. Generated files are kept.</Label><ErrorNotice error={action.error} /></DialogBody></Sheet>}{editing && <Sheet centered title="Rename thread" onClose={() => setEditing(undefined)}><DialogBody actions={<><Button title="Cancel" text onPress={() => setEditing(undefined)} /><Button title="Save" text disabled={action.busy} onPress={() => void action.run(async () => { await session.client.task({ ...destination, threadId: editing }, 'PATCH', { title: newTitle.trim() }); setEditing(undefined); await session.refresh(); })} /></>}><Input label="Title" accessibilityLabel="Thread title" value={newTitle} onChangeText={setNewTitle} /></DialogBody></Sheet>}</>;
}
