import { skins, type Skin } from './core/skins';
import React, { createContext, useContext, useRef, useState } from 'react';
import { ActivityIndicator, Dimensions, KeyboardAvoidingView, Modal, Platform, Pressable, ScrollView, StatusBar, StyleSheet, Switch, Text, TextInput, View, useColorScheme, type TextInputProps, type TextProps, type StyleProp, type ViewStyle } from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { Icon, type IconName } from './Icon';

const light = { dark: false, mineText: '#FFFFFF', accentInk: '#FFFFFF', bg: '#FEF7FF', card: '#F3EDF7', text: '#1D1B20', muted: '#49454F', line: '#CAC4D0', accent: '#009957', tint: '#E8DEF8', danger: '#B3261E', chrome: '#ECE6F0', mine: '#377FE6', bubble: '#E9E9EB', outline: '#79747E', sheet: '#F7F2FA' };
const dark: typeof light = { dark: true, mineText: '#FFFFFF', accentInk: '#FFFFFF', bg: '#141218', card: '#211F26', text: '#E6E0E9', muted: '#CAC4D0', line: '#49454F', accent: '#009957', tint: '#4A4458', danger: '#F2B8B5', chrome: '#2B2930', mine: '#377FE6', bubble: '#262629', outline: '#938F99', sheet: '#1D1B20' };
const Theme = createContext(light);
const DialogTypography = createContext(false);
export const useTheme = () => useContext(Theme);
export function ThemeProvider({ children, skin = 'system' }: React.PropsWithChildren<{ skin?: Skin | 'system' }>) { const scheme = useColorScheme(); return <Theme.Provider value={skin !== 'system' && skin in skins ? skins[skin] : scheme === 'dark' ? dark : light}>{children}</Theme.Provider>; }
export function Label({ children, muted, large, bold, size, style, ...props }: TextProps & { muted?: boolean; large?: boolean; bold?: boolean; size?: number }) {
  const c = useTheme(); const dialog = useContext(DialogTypography); const fontSize = size ?? (large ? 24 : dialog ? 14 : 15); return <Text {...props} style={[{ color: muted ? c.muted : c.text, fontSize, lineHeight: fontSize >= 24 ? fontSize + 8 : dialog ? 20 : 24, includeFontPadding: false, letterSpacing: (size ?? 15) >= 24 ? 0 : bold && size === 14 ? 0.1 : dialog ? 0 : 0.5, fontWeight: bold ? '600' : '400' }, style]}>{children}</Text>;
}
export function Button({ title, onPress, disabled, danger, primary, tonal, text, style }: { title: string; onPress: () => void; disabled?: boolean; danger?: boolean; primary?: boolean; tonal?: boolean; text?: boolean; style?: StyleProp<ViewStyle> }) {
  const c = useTheme(); return <Pressable accessibilityRole="button" accessibilityLabel={title} accessibilityState={{ disabled }} disabled={disabled} onPress={onPress}
    style={({ pressed }) => [{ minHeight: 40, paddingHorizontal: text ? 12 : 24, paddingVertical: 10, borderRadius: 24, backgroundColor: primary ? disabled ? c.text + '1F' : c.accent : tonal ? c.tint : 'transparent', borderWidth: text || primary || tonal ? 0 : 1, borderColor: c.outline, opacity: disabled && !primary ? 0.38 : pressed ? 0.65 : 1, justifyContent: 'center' }, style]}>
    <Text style={{ color: disabled ? c.text + '61' : danger ? c.danger : primary ? c.accentInk : tonal ? c.text : c.accent, fontWeight: '500', textAlign: 'center', fontSize: 14, lineHeight: 20, includeFontPadding: false, letterSpacing: 0.1 }}>{title}</Text>
  </Pressable>;
}
export function IconButton({ icon, label, onPress, size = 44, glyph = 20, chrome = true, color, disabled, surface, elevation = 3 }: { icon: IconName; label: string; onPress: () => void; size?: number; glyph?: number; chrome?: boolean; color?: string; disabled?: boolean; surface?: string; elevation?: number }) {
  const c = useTheme(); return <Pressable accessibilityRole="button" accessibilityLabel={label} disabled={disabled} onPress={onPress} style={{ width: Math.max(48, size), height: Math.max(48, size), alignItems: 'center', justifyContent: 'center', opacity: disabled ? 0.38 : 1 }}><View style={[{ width: size, height: size, borderRadius: size / 2, alignItems: 'center', justifyContent: 'center' }, chrome && { backgroundColor: surface ?? c.chrome, elevation, shadowColor: '#000', shadowOpacity: elevation ? 0.16 : 0, shadowRadius: 3, shadowOffset: { width: 0, height: 2 } }]}><Icon name={icon} size={glyph} color={color ?? c.text} /></View></Pressable>;
}
export function Input({ label, style, onFocus, onBlur, ...props }: TextInputProps & { label?: string }) {
  const c = useTheme(); const [focused, setFocused] = useState(false); const floating = !!props.value || focused;
  return <View style={{ paddingTop: label ? 8 : 0 }}><TextInput {...props} onFocus={e => { setFocused(true); onFocus?.(e); }} onBlur={e => { setFocused(false); onBlur?.(e); }} accessibilityLabel={label ?? props.accessibilityLabel} placeholder={props.placeholder ?? (!floating ? label : undefined)} placeholderTextColor={c.muted} style={[{ borderWidth: focused ? 2 : 1, borderColor: focused ? c.accent : c.outline, borderRadius: 4, color: c.text, fontSize: 16, letterSpacing: 0.5, paddingHorizontal: 16, paddingVertical: 15, minHeight: 56, textAlignVertical: props.multiline ? 'top' : 'center' }, style]} />{label && floating && <Text pointerEvents="none" style={{ position: 'absolute', left: 12, top: 0, paddingHorizontal: 4, color: focused ? c.accent : c.muted, backgroundColor: c.bg, fontSize: 12, letterSpacing: 0.4, lineHeight: 16, includeFontPadding: false }}>{label}</Text>}</View>;
}
export function Card({ children, gap = 10 }: React.PropsWithChildren<{ gap?: number }>) { const c = useTheme(); return <View style={{ backgroundColor: c.dark ? '#36343B' : '#E7E0EC', borderRadius: 12, padding: 16, gap }}>{children}</View>; }
export function Row({ children, style }: React.PropsWithChildren<{ style?: StyleProp<ViewStyle> }>) { return <View style={[styles.row, style]}>{children}</View>; }
export function Page({ children }: React.PropsWithChildren) { const c = useTheme(); return <ScrollView keyboardShouldPersistTaps="handled" style={{ backgroundColor: c.bg, flex: 1 }} contentContainerStyle={styles.page}>{children}</ScrollView>; }
export function Header({ title, onBack, trailing }: { title: string; onBack: () => void; trailing?: React.ReactNode }) { const c = useTheme(); return <View style={{ borderBottomWidth: 1, borderColor: c.line, flexDirection: 'row', alignItems: 'center', gap: 10, paddingHorizontal: 10, paddingVertical: 8 }}><IconButton icon="back" label="Back" onPress={onBack} size={32} glyph={20} surface={c.muted + '26'} elevation={0} /><Label size={17} bold style={{ flex: 1 }}>{title}</Label>{trailing}</View>; }
export function Section({ title, children }: React.PropsWithChildren<{ title: string }>) { const c = useTheme(); return <View style={{ gap: 10 }}>{!!title && <Label size={12} muted bold>{title.toUpperCase()}</Label>}<View style={{ height: 1, backgroundColor: c.line }} />{children}</View>; }
export function ValueRow({ title, value, onPress }: { title: string; value: string; onPress: () => void }) { const c = useTheme(); return <Pressable accessibilityRole="button" accessibilityLabel={title} onPress={onPress} style={{ minHeight: 48, flexDirection: 'row', alignItems: 'center', gap: 10 }}><Label muted style={{ flex: 1 }}>{title}</Label><Label style={{ color: c.accent }}>{value}</Label></Pressable>; }
export function SettingRow({ title, value, onPress, danger, icon }: { title: string; value?: string; onPress?: () => void; danger?: boolean; icon?: IconName }) { const c = useTheme(); return <Pressable accessibilityRole={onPress ? 'button' : undefined} disabled={!onPress} onPress={onPress} style={{ minHeight: onPress ? 48 : 24, padding: onPress ? 12 : 0, flexDirection: 'row', alignItems: 'center', gap: 10 }}>
  {icon && <Icon name={icon} color={c.accent} size={20} />}<Label size={onPress ? 14 : 15} style={{ lineHeight: onPress ? 20 : 24, fontWeight: onPress ? '500' : '400', letterSpacing: onPress ? 0.1 : 0.5, flex: 1, color: danger ? c.danger : onPress ? c.accent : c.muted }}>{title}</Label>{value && <Label style={{ maxWidth: '65%', textAlign: 'right' }}>{value}</Label>}</Pressable>; }
export function Sheet({ children, title, onClose, action, centered = false, full = false, tonal = false }: React.PropsWithChildren<{ title?: string; onClose: () => void; action?: React.ReactNode; centered?: boolean; full?: boolean; tonal?: boolean }>) {
  const c = useTheme(); const insets = useSafeAreaInsets();
  return <Modal transparent animationType="fade" onRequestClose={onClose} statusBarTranslucent>{centered && Platform.OS === 'android' && <StatusBar barStyle="light-content" />}<KeyboardAvoidingView behavior={Platform.OS === 'ios' ? 'padding' : 'height'} style={{ flex: 1, justifyContent: centered ? 'center' : 'flex-end', backgroundColor: centered ? '#00000099' : '#00000052', paddingTop: centered ? insets.top : 0, paddingBottom: centered ? insets.bottom : 0 }}><Pressable accessibilityLabel="Dismiss" onPress={onClose} style={StyleSheet.absoluteFill} /><View style={{ backgroundColor: centered ? tonal ? c.dark ? '#10261F' : '#E3EDED' : c.chrome : c.sheet, borderRadius: 28, borderBottomLeftRadius: centered ? 28 : 0, borderBottomRightRadius: centered ? 28 : 0, marginHorizontal: centered ? 46 : 0, height: full ? '100%' : undefined, maxHeight: full ? '100%' : centered ? '84%' : '92%', paddingBottom: centered ? tonal ? 16 : 24 : Math.max(insets.bottom, 16), paddingTop: full ? insets.top + 22 : centered ? tonal ? 16 : 24 : 22 }}>
    {!centered && <View style={{ width: 32, height: 4, borderRadius: 2, backgroundColor: c.outline, alignSelf: 'center', marginBottom: 22 }} />}
    {title && <View style={{ flexDirection: 'row', alignItems: 'center', paddingHorizontal: centered ? tonal ? 20 : 24 : 4, minHeight: centered && !tonal ? 32 : 48 }}>
      {!centered && <Button title="Cancel" text onPress={onClose} style={{ paddingHorizontal: 12 }} />}<Label bold={!centered || tonal} size={centered ? tonal ? 18 : 24 : 17} style={{ flex: 1, textAlign: centered ? 'left' : 'center' }}>{title}</Label>{action ?? (!centered ? <Button title="Done" text onPress={onClose} style={{ paddingHorizontal: 12 }} /> : null)}</View>}
    <Theme.Provider value={{ ...c, bg: centered ? tonal ? c.dark ? '#10261F' : '#E3EDED' : c.chrome : c.sheet }}><DialogTypography.Provider value={centered && !tonal}>{children}</DialogTypography.Provider></Theme.Provider>
  </View></KeyboardAvoidingView></Modal>;
}
export function ErrorNotice({ error }: { error?: string }) { const c = useTheme(); return error ? <Text accessibilityRole="alert" style={{ color: c.danger, fontSize: 14, paddingVertical: 8 }}>{error}</Text> : null; }
export function useAction() {
  const [busy, setBusy] = useState(false); const [error, setError] = useState<string>(); const pending = useRef(false);
  const run = async (fn: () => Promise<unknown>) => { if (pending.current) return; pending.current = true; setBusy(true); setError(undefined); try { await fn(); } catch (e) { setError(e instanceof Error ? e.message : 'Something went wrong. Try again.'); } finally { pending.current = false; setBusy(false); } };
  return { busy, error, run, clearError: () => setError(undefined) };
}
export function Loading() { const c = useTheme(); return <ActivityIndicator accessibilityLabel="Loading" color={c.accent} style={{ padding: 24 }} />; }
export const styles = StyleSheet.create({ row: { flexDirection: 'row', alignItems: 'center', flexWrap: 'wrap', gap: 8 }, page: { paddingHorizontal: 20, paddingVertical: 16, gap: 20, width: '100%', maxWidth: Platform.OS === 'ios' ? 820 : undefined, alignSelf: 'center', paddingBottom: 36 } });

export function FormSection({ title, footer, children }: React.PropsWithChildren<{ title?: string; footer?: string }>) { return <View style={{ paddingHorizontal: 20, gap: 10 }}>{title && <Label size={12} muted bold>{title.toUpperCase()}</Label>}<View style={{ height: 1, backgroundColor: useTheme().line }} />{children}{footer && <Label size={13} muted>{footer}</Label>}</View>; }
export function Choice({ label, value, options, onChange, disabled }: { label: string; value: string; options: { id: string; label: string }[]; onChange: (id: string) => void; disabled?: boolean }) { const [anchor, setAnchor] = useState<{ x: number; y: number; width: number; height: number }>(); const target = useRef<View>(null); const c = useTheme(); return <><View ref={target} collapsable={false}><Pressable accessibilityRole="button" accessibilityLabel={label} disabled={disabled} onPress={() => target.current?.measureInWindow((x,y,width,height) => setAnchor({ x,y,width,height }))} style={{ opacity: disabled ? 0.5 : 1 }}><View pointerEvents="none"><Input label={label} value={options.find(o => o.id === value)?.label ?? value} editable={false} /></View><View style={{ position: 'absolute', right: 12, top: 24 }}><Icon name="dropdown" color={c.muted} /></View></Pressable></View>{anchor && <Modal transparent animationType="fade" onRequestClose={() => setAnchor(undefined)} statusBarTranslucent><Pressable style={{ flex: 1 }} onPress={() => setAnchor(undefined)}><View style={{ position: 'absolute', left: anchor.x, top: Math.min(anchor.y + anchor.height, Dimensions.get('window').height - Math.min(options.length * 48 + 16, 320) - 32), width: anchor.width, maxHeight: 320, paddingVertical: 8, borderRadius: 4, backgroundColor: c.card, elevation: 8 }}><ScrollView>{options.map(o => <Pressable key={o.id} onPress={() => { onChange(o.id); setAnchor(undefined); }} style={{ minHeight: 48, paddingHorizontal: 12, justifyContent: 'center' }}><Label size={16}>{o.label}</Label></Pressable>)}</ScrollView></View></Pressable></Modal>}</>; }

export function ActionRow({ title, icon, onPress, disabled, danger, color: tint, fontSize = 15 }: { title: string; icon?: IconName; onPress: () => void; disabled?: boolean; danger?: boolean; color?: string; fontSize?: number }) { const c = useTheme(); const color = disabled ? c.muted + '80' : danger ? c.danger : tint ?? c.accent; return <Pressable accessibilityRole="button" accessibilityLabel={title} disabled={disabled} onPress={onPress} style={{ minHeight: 48, flexDirection: 'row', alignItems: 'center', gap: 12 }}>{icon && <Icon name={icon} size={20} color={color} />}<Label size={fontSize} style={{ color }}>{title}</Label></Pressable>; }

export function RadioRow({ title, selected, onPress, disabled, icon }: { title: string; selected: boolean; onPress: () => void; disabled?: boolean; icon?: IconName }) { const c = useTheme(); return <Pressable accessibilityRole="radio" accessibilityState={{ checked: selected, disabled }} onPress={onPress} disabled={disabled} style={{ minHeight: 48, flexDirection: 'row', alignItems: 'center', gap: 12, opacity: disabled ? 0.38 : 1 }}><View style={{ width: 20, height: 20, marginLeft: 2, marginRight: 2, borderRadius: 10, borderWidth: 2, borderColor: selected ? c.accent : c.muted, alignItems: 'center', justifyContent: 'center' }}>{selected && <View style={{ width: 10, height: 10, borderRadius: 5, backgroundColor: c.accent }} />}</View>{icon && <Icon name={icon} size={20} color={c.muted} />}<Label size={15}>{title}</Label></Pressable>; }

export function Toggle({ label, value, onChange, disabled }: { label: string; value: boolean; onChange: (value: boolean) => void; disabled?: boolean }) {
 const c = useTheme();
 if (Platform.OS !== 'android') return <Switch accessibilityLabel={label} value={value} onValueChange={onChange} disabled={disabled} trackColor={{ true: c.accent }} />;
 return <Pressable accessibilityRole="switch" accessibilityLabel={label} accessibilityState={{ checked: value, disabled }} disabled={disabled} onPress={() => onChange(!value)} style={{ width: 52, height: 48, justifyContent: 'center', opacity: disabled ? .38 : 1 }}><View style={{ width: 52, height: 32, borderRadius: 16, borderWidth: value ? 0 : 2, borderColor: c.outline, backgroundColor: value ? c.accent : c.chrome, justifyContent: 'center', alignItems: value ? 'flex-end' : 'flex-start', paddingHorizontal: value ? 4 : 6 }}><View style={{ width: value ? 24 : 16, height: value ? 24 : 16, borderRadius: 12, backgroundColor: value ? '#FFFFFF' : c.outline }} /></View></Pressable>;
}

export function DialogBody({ children, actions, gap = 8 }: React.PropsWithChildren<{ actions: React.ReactNode; gap?: number }>) { return <View style={{ paddingHorizontal: 24, paddingTop: 16 }}><View style={{ gap }}>{children}</View><Row style={{ marginTop: 24, minHeight: 48, justifyContent: 'flex-end', flexWrap: 'nowrap' }}>{actions}</Row></View>; }
