import { skins, type Skin } from './core/skins';
import React, { createContext, useContext, useRef, useState } from 'react';
import { ActivityIndicator, Animated, Dimensions, KeyboardAvoidingView, Modal, Platform, Pressable, ScrollView, StatusBar, StyleSheet, Switch, Text, TextInput, View, useColorScheme, useWindowDimensions, type TextInputProps, type TextProps, type StyleProp, type ViewStyle } from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { Icon, type IconName } from './Icon';
import { useSheetSlide } from './useSheetSlide';

const light = { dark: false, mineText: '#FFFFFF', accentInk: '#FFFFFF', bg: '#FEF7FF', card: '#F3EDF7', text: '#1D1B20', muted: '#49454F', line: '#CAC4D0', accent: '#009957', tint: '#E8DEF8', danger: '#B3261E', chrome: '#ECE6F0', mine: '#377FE6', bubble: '#E9E9EB', outline: '#79747E', sheet: '#F7F2FA' };
const dark: typeof light = { dark: true, mineText: '#FFFFFF', accentInk: '#FFFFFF', bg: '#141218', card: '#211F26', text: '#E6E0E9', muted: '#CAC4D0', line: '#49454F', accent: '#009957', tint: '#4A4458', danger: '#F2B8B5', chrome: '#2B2930', mine: '#377FE6', bubble: '#262629', outline: '#938F99', sheet: '#1D1B20' };
const Theme = createContext(light);
const DialogTypography = createContext(false);
const SettingsStyle = createContext(false);
const SettingsSectionDepth = createContext(0);
export const useSettingsStyle = () => useContext(SettingsStyle);
/** Settings-only surfaces; custom app palettes remain available. */
export function SettingsSurface({ children, modal = false }: React.PropsWithChildren<{ modal?: boolean }>) {
  const c = useTheme();
  const theme = c.dark
    ? { ...c, bg: '#000000', sheet: '#171717', card: '#202020', chrome: '#292929', text: '#FFFFFF', muted: '#A7A7A7', line: '#303030', outline: '#5E5E5E', accent: '#FFFFFF', accentInk: '#000000' }
    : { ...c, bg: '#F5F6F6', sheet: '#FFFFFF', card: '#F0F0F0', chrome: '#E6E6E6', text: '#0A0A0A', muted: '#747474', line: '#E8E8E8', outline: '#A2A2A2', accent: '#111111', accentInk: '#FFFFFF' };
  return <SettingsStyle.Provider value><Theme.Provider value={theme}>{modal ? children : <View style={{ flex: 1, backgroundColor: theme.bg }}>{children}</View>}</Theme.Provider></SettingsStyle.Provider>;
}
export const useTheme = () => useContext(Theme);
export function ThemeProvider({ children, skin = 'system' }: React.PropsWithChildren<{ skin?: Skin | 'system' }>) { const scheme = useColorScheme(); return <Theme.Provider value={skin !== 'system' && skin in skins ? skins[skin] : scheme === 'dark' ? dark : light}>{children}</Theme.Provider>; }
export function Label({ children, muted, large, bold, size, style, ...props }: TextProps & { muted?: boolean; large?: boolean; bold?: boolean; size?: number }) {
  const c = useTheme(); const settings = useSettingsStyle(); const dialog = useContext(DialogTypography); const fontSize = size ?? (large ? 24 : dialog ? 14 : 15); return <Text {...props} style={[{ color: muted ? c.muted : c.text, fontSize, lineHeight: fontSize >= 24 ? fontSize + 8 : settings ? fontSize + 6 : dialog ? 20 : 24, includeFontPadding: false, letterSpacing: settings ? 0 : (size ?? 15) >= 24 ? 0 : bold && size === 14 ? 0.1 : dialog ? 0 : 0.5, fontWeight: bold ? '600' : '400' }, style]}>{children}</Text>;
}
export function Button({ title, onPress, disabled, danger, primary, tonal, text, style }: { title: string; onPress: () => void; disabled?: boolean; danger?: boolean; primary?: boolean; tonal?: boolean; text?: boolean; style?: StyleProp<ViewStyle> }) {
  const c = useTheme(); const settings = useSettingsStyle(); return <Pressable accessibilityRole="button" accessibilityLabel={title} accessibilityState={{ disabled }} disabled={disabled} onPress={onPress}
    style={({ pressed }) => [{ minHeight: settings ? 44 : 40, paddingHorizontal: text ? 12 : 24, paddingVertical: 10, borderRadius: 24, backgroundColor: primary ? disabled ? c.text + '1F' : c.accent : tonal ? c.tint : settings && !text ? c.chrome : 'transparent', borderWidth: settings || text || primary || tonal ? 0 : 1, borderColor: c.outline, opacity: disabled && !primary ? 0.38 : pressed ? 0.65 : 1, justifyContent: 'center' }, style]}>
    <Text style={{ color: disabled ? c.text + '61' : danger ? c.danger : primary ? c.accentInk : tonal ? c.text : c.accent, fontWeight: '500', textAlign: 'center', fontSize: 14, lineHeight: 20, includeFontPadding: false, letterSpacing: 0.1 }}>{title}</Text>
  </Pressable>;
}
export function IconButton({ icon, label, onPress, size = 44, glyph = 20, chrome = true, color, disabled, surface, elevation = 3 }: { icon: IconName; label: string; onPress: () => void; size?: number; glyph?: number; chrome?: boolean; color?: string; disabled?: boolean; surface?: string; elevation?: number }) {
  const c = useTheme(); return <Pressable accessibilityRole="button" accessibilityLabel={label} disabled={disabled} onPress={onPress} style={{ width: Math.max(48, size), height: Math.max(48, size), alignItems: 'center', justifyContent: 'center', opacity: disabled ? 0.38 : 1 }}><View style={[{ width: size, height: size, borderRadius: size / 2, alignItems: 'center', justifyContent: 'center' }, chrome && { backgroundColor: surface ?? c.chrome, elevation, shadowColor: '#000', shadowOpacity: elevation ? 0.16 : 0, shadowRadius: 3, shadowOffset: { width: 0, height: 2 } }]}><Icon name={icon} size={glyph} color={color ?? c.text} /></View></Pressable>;
}
export function Input({ label, style, onFocus, onBlur, ...props }: TextInputProps & { label?: string }) {
  const c = useTheme(); const settings = useSettingsStyle(); const [focused, setFocused] = useState(false); const floating = !!props.value || focused;
  if (settings) return <View style={{ gap: 6 }}>{label && <Label size={12} muted style={{ paddingHorizontal: 4 }}>{label}</Label>}<TextInput {...props} onFocus={e => { setFocused(true); onFocus?.(e); }} onBlur={e => { setFocused(false); onBlur?.(e); }} accessibilityLabel={label ?? props.accessibilityLabel} placeholderTextColor={c.muted} style={[{ minHeight: 52, backgroundColor: c.card, borderWidth: focused ? 1 : 0, borderColor: c.accent, borderRadius: 14, color: c.text, fontSize: 15, paddingHorizontal: 14, paddingVertical: 14, textAlignVertical: props.multiline ? 'top' : 'center' }, style]} /></View>;
  return <View style={{ paddingTop: label ? 8 : 0 }}><TextInput {...props} onFocus={e => { setFocused(true); onFocus?.(e); }} onBlur={e => { setFocused(false); onBlur?.(e); }} accessibilityLabel={label ?? props.accessibilityLabel} placeholder={props.placeholder ?? (!floating ? label : undefined)} placeholderTextColor={c.muted} style={[{ borderWidth: focused ? 2 : 1, borderColor: focused ? c.accent : c.outline, borderRadius: 4, color: c.text, fontSize: 16, letterSpacing: 0.5, paddingHorizontal: 16, paddingVertical: 15, minHeight: 56, textAlignVertical: props.multiline ? 'top' : 'center' }, style]} />{label && floating && <Text pointerEvents="none" style={{ position: 'absolute', left: 12, top: 0, paddingHorizontal: 4, color: focused ? c.accent : c.muted, backgroundColor: c.bg, fontSize: 12, letterSpacing: 0.4, lineHeight: 16, includeFontPadding: false }}>{label}</Text>}</View>;
}
export function Card({ children, gap = 10 }: React.PropsWithChildren<{ gap?: number }>) { const c = useTheme(); const settings = useSettingsStyle(); return <View style={{ backgroundColor: settings ? c.sheet : c.dark ? '#36343B' : '#E7E0EC', borderRadius: settings ? 20 : 12, padding: settings ? 14 : 16, gap }}>{children}</View>; }
export function Row({ children, style }: React.PropsWithChildren<{ style?: StyleProp<ViewStyle> }>) { return <View style={[styles.row, style]}>{children}</View>; }
export function Page({ children }: React.PropsWithChildren) { const c = useTheme(); const settings = useSettingsStyle(); return <ScrollView keyboardShouldPersistTaps="handled" style={{ backgroundColor: c.bg, flex: 1 }} contentContainerStyle={[styles.page, settings && { paddingHorizontal: 16, paddingTop: 8, gap: 16, maxWidth: 640 }]}>{children}</ScrollView>; }
export function Header({ title, onBack, trailing }: { title: string; onBack: () => void; trailing?: React.ReactNode }) { const c = useTheme(); const settings = useSettingsStyle(); if (settings) return <View style={{ minHeight: 76, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 12 }}><IconButton icon="back" label="Back" onPress={onBack} size={48} glyph={20} surface={c.sheet} elevation={0} /><Label pointerEvents="none" size={16} bold style={{ position: 'absolute', left: 64, right: 64, textAlign: 'center' }}>{title}</Label><View style={{ width: 48, height: 48, alignItems: 'center', justifyContent: 'center' }}>{trailing}</View></View>; return <View style={{ borderBottomWidth: 1, borderColor: c.line, flexDirection: 'row', alignItems: 'center', gap: 10, paddingHorizontal: 10, paddingVertical: 8 }}><IconButton icon="back" label="Back" onPress={onBack} size={32} glyph={20} surface={c.muted + '26'} elevation={0} /><Label size={17} bold style={{ flex: 1 }}>{title}</Label>{trailing}</View>; }
export function Section({ title, children }: React.PropsWithChildren<{ title: string }>) { const c = useTheme(); const settings = useSettingsStyle(); const depth = useContext(SettingsSectionDepth); if (settings && depth > 0) return <View style={{ gap: 10, paddingVertical: 10, borderTopWidth: 1, borderTopColor: c.line }}>{!!title && <Label size={14} bold>{title}</Label>}{children}</View>; if (settings) return <View style={{ gap: 8 }}>{!!title && <Label size={13} muted style={{ paddingHorizontal: 8 }}>{title}</Label>}<SettingsSectionDepth.Provider value={depth + 1}><View style={{ gap: 10, backgroundColor: c.sheet, borderRadius: 20, paddingHorizontal: 14, paddingVertical: 12, overflow: 'hidden' }}>{children}</View></SettingsSectionDepth.Provider></View>; return <View style={{ gap: 10 }}>{!!title && <Label size={12} muted bold>{title.toUpperCase()}</Label>}<View style={{ height: 1, backgroundColor: c.line }} />{children}</View>; }
export function ValueRow({ title, value, onPress }: { title: string; value: string; onPress: () => void }) { const c = useTheme(); return <Pressable accessibilityRole="button" accessibilityLabel={title} onPress={onPress} style={{ minHeight: 48, flexDirection: 'row', alignItems: 'center', gap: 10 }}><Label muted style={{ flex: 1 }}>{title}</Label><Label style={{ color: c.accent }}>{value}</Label></Pressable>; }
export function SettingRow({ title, value, onPress, danger, icon, subtitle }: { title: string; value?: string; onPress?: () => void; danger?: boolean; icon?: IconName; iconColor?: string; subtitle?: string }) { const c = useTheme(); const settings = useSettingsStyle(); return <Pressable accessibilityRole={onPress ? 'button' : undefined} disabled={!onPress} onPress={onPress} style={({ pressed }) => ({ minHeight: settings ? subtitle ? 76 : 62 : onPress ? 48 : 24, paddingHorizontal: settings ? 2 : onPress ? 12 : 0, paddingVertical: settings ? 10 : onPress ? 12 : 0, flexDirection: 'row', alignItems: 'center', gap: 12, ...(settings ? { borderBottomWidth: 1, borderBottomColor: c.line, marginVertical: -5, opacity: pressed ? 0.55 : 1 } : {}) })}>
  {icon && (settings ? <View style={{ width: 36, height: 36, borderRadius: 18, backgroundColor: c.dark ? '#080808' : '#BDBDBD', alignItems: 'center', justifyContent: 'center' }}><Icon name={icon} color="#FFFFFF" size={18} /></View> : <Icon name={icon} color={c.accent} size={20} />)}<View style={{ flex: 1, gap: 2 }}><Label size={settings ? 15 : onPress ? 14 : 15} style={{ lineHeight: settings ? 21 : 20, fontWeight: settings ? '400' : onPress ? '500' : '400', letterSpacing: settings || onPress ? 0 : 0.5, color: danger ? c.danger : settings ? c.text : onPress ? c.accent : c.muted }}>{title}</Label>{subtitle && <Label size={12} muted style={{ lineHeight: 17 }}>{subtitle}</Label>}</View>{value && <Label size={settings ? 14 : 15} muted={settings} style={{ maxWidth: settings ? '42%' : '65%', textAlign: 'right', lineHeight: 19 }}>{value}</Label>}{settings && onPress && <Icon name="chevron" size={17} color={c.text} />}</Pressable>; }
export function Sheet({ children, title, onClose, action, centered = false, full = false, tonal = false, slide = false, swipeToDismiss = false, closing = false, onDismiss, closeLabel = 'Cancel', headerPaddingHorizontal }: React.PropsWithChildren<{ title?: string; closeLabel?: string; headerPaddingHorizontal?: number; onClose: () => void; action?: React.ReactNode; centered?: boolean; full?: boolean; tonal?: boolean; slide?: boolean; swipeToDismiss?: boolean; closing?: boolean; onDismiss?: () => void }>) {
  const c = useTheme(); const insets = useSafeAreaInsets(); const settings = useSettingsStyle();
  const settingsPage = settings && full && !centered;
  const surface = settingsPage ? c.bg : centered ? tonal ? c.dark ? '#10261F' : '#E3EDED' : c.chrome : c.sheet;
  const viewport = useWindowDimensions();
  const draggable = swipeToDismiss && slide && !centered && !full;
  const motion = useSheetSlide(slide, closing, onDismiss, { enabled: draggable, height: viewport.height, onClose });
  return <Modal transparent animationType={slide ? 'none' : 'fade'} onShow={slide ? motion.onShow : undefined} onRequestClose={onClose} statusBarTranslucent>{centered && Platform.OS === 'android' && <StatusBar barStyle="light-content" />}<KeyboardAvoidingView behavior={Platform.OS === 'ios' ? 'padding' : 'height'} style={{ flex: 1, justifyContent: centered ? 'center' : 'flex-end', backgroundColor: slide ? 'transparent' : centered ? '#00000099' : '#00000052', paddingTop: centered ? insets.top : 0, paddingBottom: centered ? insets.bottom : 0 }}>
    {slide && <Animated.View pointerEvents="none" style={[StyleSheet.absoluteFill, { backgroundColor: '#00000052', opacity: motion.progress.interpolate({ inputRange: [0, 1], outputRange: [1, 0] }) }]} />}
    <Pressable accessibilityLabel="Dismiss" onPress={onClose} style={StyleSheet.absoluteFill} /><Animated.View pointerEvents={closing ? 'none' : 'auto'} style={{ ...(slide ? { transform: [{ translateY: motion.progress.interpolate({ inputRange: [0, 1], outputRange: [0, viewport.height] }) }] } : {}), backgroundColor: surface, borderRadius: settingsPage ? 0 : 28, borderBottomLeftRadius: centered ? 28 : 0, borderBottomRightRadius: centered ? 28 : 0, marginHorizontal: centered ? 46 : 0, height: full ? '100%' : undefined, maxHeight: full ? '100%' : centered ? '84%' : '92%', paddingBottom: centered ? tonal ? 16 : 24 : Math.max(insets.bottom, 16), paddingTop: full ? insets.top + (settingsPage ? 0 : 22) : centered ? tonal ? 16 : 24 : 22 }}>
    <View {...(draggable ? motion.panHandlers : {})} collapsable={!draggable} testID={draggable ? "sheet-drag-area" : undefined} style={draggable ? { marginTop: -22, paddingTop: 22 } : undefined}>
    {!centered && !settingsPage && <View style={{ width: 32, height: 4, borderRadius: 2, backgroundColor: c.outline, alignSelf: 'center', marginBottom: 22 }} />}
    {title && <View style={{ flexDirection: 'row', alignItems: 'center', paddingHorizontal: headerPaddingHorizontal ?? (centered ? tonal ? 20 : 24 : 4), minHeight: centered && !tonal ? 32 : 48 }}>
      {!centered && <Button title={closeLabel} text onPress={onClose} style={{ paddingHorizontal: 12 }} />}<Label bold={!centered || tonal} size={centered ? tonal ? 18 : 24 : 17} style={{ flex: 1, textAlign: centered ? 'left' : 'center' }}>{title}</Label>{action ?? (!centered ? <Button title="Done" text onPress={onClose} style={{ paddingHorizontal: 12 }} /> : null)}</View>}
    </View>
    <Theme.Provider value={{ ...c, bg: surface }}><DialogTypography.Provider value={centered && !tonal}>{children}</DialogTypography.Provider></Theme.Provider>
  </Animated.View></KeyboardAvoidingView></Modal>;
}
export function ErrorNotice({ error }: { error?: string }) { const c = useTheme(); return error ? <Text accessibilityRole="alert" style={{ color: c.danger, fontSize: 14, paddingVertical: 8 }}>{error}</Text> : null; }
export function useAction() {
  const [busy, setBusy] = useState(false); const [error, setError] = useState<string>(); const pending = useRef(false);
  const run = async (fn: () => Promise<unknown>) => { if (pending.current) return; pending.current = true; setBusy(true); setError(undefined); try { await fn(); } catch (e) { setError(e instanceof Error ? e.message : 'Something went wrong. Try again.'); } finally { pending.current = false; setBusy(false); } };
  return { busy, error, run, clearError: () => setError(undefined) };
}
export function Loading() { const c = useTheme(); return <ActivityIndicator accessibilityLabel="Loading" color={c.accent} style={{ padding: 24 }} />; }
export const styles = StyleSheet.create({ row: { flexDirection: 'row', alignItems: 'center', flexWrap: 'wrap', gap: 8 }, page: { paddingHorizontal: 20, paddingVertical: 16, gap: 20, width: '100%', maxWidth: Platform.OS === 'ios' ? 820 : undefined, alignSelf: 'center', paddingBottom: 36 } });

export function FormSection({ title, footer, children }: React.PropsWithChildren<{ title?: string; footer?: string }>) { const c = useTheme(); const settings = useSettingsStyle(); if (settings) return <View style={{ marginHorizontal: 16, gap: 8 }}>{title && <Label size={13} muted style={{ paddingHorizontal: 8 }}>{title}</Label>}<View style={{ backgroundColor: c.sheet, borderRadius: 20, paddingHorizontal: 14, paddingVertical: 12, gap: 10, overflow: 'hidden' }}>{children}{footer && <Label size={13} muted>{footer}</Label>}</View></View>; return <View style={{ paddingHorizontal: 20, gap: 10 }}>{title && <Label size={12} muted bold>{title.toUpperCase()}</Label>}<View style={{ height: 1, backgroundColor: c.line }} />{children}{footer && <Label size={13} muted>{footer}</Label>}</View>; }
export function Choice({ label, value, options, onChange, disabled }: { label: string; value: string; options: { id: string; label: string }[]; onChange: (id: string) => void; disabled?: boolean }) { const [anchor, setAnchor] = useState<{ x: number; y: number; width: number; height: number }>(); const target = useRef<View>(null); const c = useTheme(); const settings = useSettingsStyle(); return <><View ref={target} collapsable={false}><Pressable accessibilityRole="button" accessibilityLabel={label} disabled={disabled} onPress={() => target.current?.measureInWindow((x,y,width,height) => setAnchor({ x,y,width,height }))} style={{ opacity: disabled ? 0.5 : 1 }}><View pointerEvents="none"><Input label={label} value={options.find(o => o.id === value)?.label ?? value} editable={false} style={settings ? { paddingRight: 36 } : undefined} /></View><View style={{ position: 'absolute', right: 12, top: settings ? 43 : 24 }}><Icon name="dropdown" color={c.muted} /></View></Pressable></View>{anchor && <Modal transparent animationType="fade" onRequestClose={() => setAnchor(undefined)} statusBarTranslucent><Pressable style={{ flex: 1 }} onPress={() => setAnchor(undefined)}><View style={{ position: 'absolute', left: anchor.x, top: Math.min(anchor.y + anchor.height, Dimensions.get('window').height - Math.min(options.length * 48 + 16, 320) - 32), width: anchor.width, maxHeight: 320, paddingVertical: 8, borderRadius: settings ? 16 : 4, backgroundColor: c.card, elevation: 8 }}><ScrollView>{options.map(o => <Pressable key={o.id} onPress={() => { onChange(o.id); setAnchor(undefined); }} style={{ minHeight: 48, paddingHorizontal: 12, justifyContent: 'center' }}><Label size={16}>{o.label}</Label></Pressable>)}</ScrollView></View></Pressable></Modal>}</>; }

export function ActionRow({ title, icon, onPress, disabled, danger, color: tint, fontSize = 15 }: { title: string; icon?: IconName; onPress: () => void; disabled?: boolean; danger?: boolean; color?: string; fontSize?: number }) { const c = useTheme(); const color = disabled ? c.muted + '80' : danger ? c.danger : tint ?? c.accent; return <Pressable accessibilityRole="button" accessibilityLabel={title} disabled={disabled} onPress={onPress} style={{ minHeight: 48, flexDirection: 'row', alignItems: 'center', gap: 12 }}>{icon && <Icon name={icon} size={20} color={color} />}<Label size={fontSize} style={{ color }}>{title}</Label></Pressable>; }

export function RadioRow({ title, selected, onPress, disabled, icon }: { title: string; selected: boolean; onPress: () => void; disabled?: boolean; icon?: IconName }) { const c = useTheme(); return <Pressable accessibilityRole="radio" aria-checked={selected} accessibilityState={{ checked: selected, disabled }} onPress={onPress} disabled={disabled} style={{ minHeight: 48, flexDirection: 'row', alignItems: 'center', gap: 12, opacity: disabled ? 0.38 : 1 }}><View style={{ width: 20, height: 20, marginLeft: 2, marginRight: 2, borderRadius: 10, borderWidth: 2, borderColor: selected ? c.accent : c.muted, alignItems: 'center', justifyContent: 'center' }}>{selected && <View style={{ width: 10, height: 10, borderRadius: 5, backgroundColor: c.accent }} />}</View>{icon && <Icon name={icon} size={20} color={c.muted} />}<Label size={15}>{title}</Label></Pressable>; }

export function Toggle({ label, value, onChange, disabled }: { label: string; value: boolean; onChange: (value: boolean) => void; disabled?: boolean }) {
 const c = useTheme(); const settings = useSettingsStyle(); const active = settings ? c.dark ? '#707070' : '#111111' : c.accent;
 if (Platform.OS !== 'android') return <Switch accessibilityLabel={label} value={value} onValueChange={onChange} disabled={disabled} trackColor={{ true: active, false: c.line }} />;
 return <Pressable accessibilityRole="switch" accessibilityLabel={label} accessibilityState={{ checked: value, disabled }} disabled={disabled} onPress={() => onChange(!value)} style={{ width: 52, height: 48, justifyContent: 'center', opacity: disabled ? .38 : 1 }}><View style={{ width: 52, height: 32, borderRadius: 16, borderWidth: value ? 0 : 2, borderColor: c.outline, backgroundColor: value ? active : c.chrome, justifyContent: 'center', alignItems: value ? 'flex-end' : 'flex-start', paddingHorizontal: value ? 4 : 6 }}><View style={{ width: value ? 24 : 16, height: value ? 24 : 16, borderRadius: 12, backgroundColor: value ? '#FFFFFF' : c.outline }} /></View></Pressable>;
}

export function DialogBody({ children, actions, gap = 8 }: React.PropsWithChildren<{ actions: React.ReactNode; gap?: number }>) { return <View style={{ paddingHorizontal: 24, paddingTop: 16 }}><View style={{ gap }}>{children}</View><Row style={{ marginTop: 24, minHeight: 48, justifyContent: 'flex-end', flexWrap: 'nowrap' }}>{actions}</Row></View>; }
