import React, { useState } from "react";
import { Pressable, ScrollView, StyleSheet, View } from "react-native";
import { Label, useTheme } from "../ui";
import { cacheStats, compactTokens, percent, tokenCount, usageLabel, usageMoney, type UsageRow, type UsageSummary, type UsageGrouping } from "../core/usage";

export function UsageTabs<T extends string>({ label, value, options, onChange }: {
  label: string; value: T; options: readonly { id: T; label: string }[]; onChange: (value: T) => void;
}) {
  const c = useTheme();
  return <View style={{ gap: 8 }}>
    <Label muted size={12}>{label}</Label>
    <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={{ gap: 6 }}>
      {options.map(option => <Pressable key={option.id} accessibilityRole="tab" accessibilityLabel={option.label}
        accessibilityState={{ selected: value === option.id }} onPress={() => onChange(option.id)}
        style={({ pressed }) => ({ minHeight: 44, paddingHorizontal: 16, paddingVertical: 11, borderRadius: 22,
          backgroundColor: value === option.id ? c.text : c.sheet, opacity: pressed ? 0.65 : 1 })}>
        <Label size={13} bold={value === option.id} style={{ color: value === option.id ? c.bg : c.muted }}>{option.label}</Label>
      </Pressable>)}
    </ScrollView>
  </View>;
}

function Metric({ title, value, detail }: { title: string; value: string; detail?: string }) {
  return <View style={{ flex: 1, minWidth: 110, gap: 2 }}>
    <Label muted size={12}>{title}</Label>
    <Label bold size={23} style={styles.numbers}>{value}</Label>
    {detail && <Label muted size={11}>{detail}</Label>}
  </View>;
}

export function UsageOverview({ data }: { data: UsageSummary }) {
  const c = useTheme();
  const { total } = data;
  const cache = cacheStats(total);
  const green = c.dark ? "#66DEAD" : "#087D57";
  const purple = c.dark ? "#BAA6F9" : "#7652BE";
  const empty = total.turns === 0;
  const segments = [
    { label: "Cached", value: cache.cached, color: green },
    { label: "Uncached", value: cache.fresh, color: purple },
    { label: "Not reported", value: cache.unknown, color: c.outline },
  ];
  return <>
    <View style={[styles.card, { backgroundColor: c.sheet }]}>
      <Label muted size={12}>TOTAL TOKENS</Label>
      <Label bold size={42} accessibilityLabel={`${tokenCount(total.input + total.output)} total tokens`} style={styles.numbers}>
        {compactTokens(total.input + total.output)}
      </Label>
      <Label muted size={12}>{tokenCount(total.turns)} model turns</Label>
      <View style={[styles.rule, { backgroundColor: c.line }]} />
      <View style={styles.metrics}>
        <Metric title="Input tokens" value={compactTokens(total.input)} detail="Read by the model" />
        <Metric title="Output tokens" value={compactTokens(total.output)} detail="Generated by the model" />
      </View>
      <View style={[styles.footer, { borderColor: c.line }]}>
        <Label muted size={12}>Reported cost</Label>
        <Label bold size={15} style={styles.numbers}>{usageMoney(total.costUsd)}</Label>
      </View>
      {(total.unpriced ?? 0) > 0 && <Label muted size={11}>Cost unavailable for {tokenCount(total.unpriced!)} of {tokenCount(total.turns)} turns.</Label>}
    </View>

    <View style={[styles.card, { backgroundColor: c.sheet }]}>
      <View style={styles.between}>
        <Label bold size={16}>Prompt cache</Label>
        <View style={{ backgroundColor: c.card, paddingHorizontal: 10, paddingVertical: 4, borderRadius: 12 }}>
          <Label size={11} muted>{empty ? "No activity" : cache.complete ? "Fully reported" : cache.rate === null ? "Not reported" : "Partially reported"}</Label>
        </View>
      </View>
      <View style={[styles.metrics, { alignItems: "flex-end" }]}>
        <View style={{ flex: 1, gap: 1 }}>
          <Label bold size={cache.rate === null ? 30 : 42} style={[styles.numbers, { color: cache.rate === null ? c.muted : green }]}>
            {empty ? "—" : percent(cache.rate)}
          </Label>
          <Label muted size={12}>Cache-hit rate</Label>
        </View>
        <View style={{ gap: 2, paddingBottom: 4 }}>
          <Label bold size={20} style={styles.numbers}>{empty ? "—" : percent(cache.coverage)}</Label>
          <Label muted size={12}>Input coverage</Label>
        </View>
      </View>
      <Label muted size={12}>{empty ? "Usage appears after a model turn finishes."
        : cache.rate === null ? "This data does not include enough cache reporting to calculate a rate."
        : cache.complete ? "The share of input tokens read from the provider’s cache."
        : "Rate uses reported input only. Missing cache data is excluded, never counted as a miss."}</Label>
      {cache.input > 0 && <>
        <View accessible accessibilityLabel={`Input tokens: ${tokenCount(cache.cached)} recorded cached, ${tokenCount(cache.fresh)} recorded uncached, ${tokenCount(cache.unknown)} without cache reporting.`}
          style={{ height: 10, borderRadius: 5, overflow: "hidden", flexDirection: "row", backgroundColor: c.chrome }}>
          {segments.filter(segment => segment.value > 0).map(segment => <View key={segment.label} style={{ flex: segment.value, backgroundColor: segment.color }} />)}
        </View>
        <View style={{ flexDirection: "row", flexWrap: "wrap", gap: 16 }}>
          {segments.filter(segment => segment.label !== "Not reported" || segment.value > 0).map(segment => <View key={segment.label} style={{ gap: 2 }}>
            <View style={{ flexDirection: "row", alignItems: "center", gap: 6 }}>
              <View style={{ width: 7, height: 7, borderRadius: 4, backgroundColor: segment.color }} />
              <Label muted size={11}>{segment.label}</Label>
            </View>
            <Label bold size={15} accessibilityLabel={`${segment.label}: ${cache.reported === 0 && segment.label !== "Not reported" && segment.value === 0 ? "unknown" : `${tokenCount(segment.value)} input tokens`}`} style={styles.numbers}>
              {cache.reported === 0 && segment.label !== "Not reported" && segment.value === 0 ? "Unknown" : compactTokens(segment.value)}
            </Label>
          </View>)}
        </View>
      </>}
    </View>

    {data.budget && data.budget.monthlyUsd > 0 && <View style={[styles.card, { backgroundColor: c.sheet }]}>
      <View style={styles.between}><Label bold>Monthly budget</Label><Label bold style={{ color: data.budget.percent >= 100 ? c.danger : c.text }}>{percent(data.budget.percent)}</Label></View>
      <Label muted size={12}>{usageMoney(data.budget.spentUsd)} of {usageMoney(data.budget.monthlyUsd)} · current month</Label>
      <View style={{ height: 6, borderRadius: 3, backgroundColor: c.chrome, overflow: "hidden" }}>
        <View style={{ height: 6, width: `${Math.min(100, Math.max(0, data.budget.percent))}%`, backgroundColor: data.budget.percent >= 100 ? c.danger : c.text }} />
      </View>
    </View>}
  </>;
}

function Detail({ label, value }: { label: string; value: string }) {
  return <View style={styles.between}><Label muted size={12}>{label}</Label><Label size={12} bold style={styles.numbers}>{value}</Label></View>;
}
function UsageBreakdownRow({ row, group, total, currency }: { row: UsageRow; group: UsageGrouping; total: number; currency: string }) {
  const c = useTheme();
  const [expanded, setExpanded] = useState(false);
  const cache = cacheStats(row);
  const name = usageLabel(row, group);
  const tokens = row.input + row.output;
  return <View style={{ backgroundColor: c.sheet, borderRadius: 20, overflow: "hidden" }}>
    <Pressable accessibilityRole="button" accessibilityLabel={`${name}, ${tokenCount(tokens)} tokens, ${usageMoney(row.costUsd)}. ${expanded ? "Hide" : "Show"} details`}
      accessibilityState={{ expanded }} onPress={() => setExpanded(!expanded)} style={({ pressed }) => ({ padding: 18, gap: 10, opacity: pressed ? 0.65 : 1 })}>
      <View style={styles.between}>
        <Label bold size={15} numberOfLines={2} style={{ flex: 1 }}>{name}</Label>
        <Label muted size={18}>{expanded ? "−" : "+"}</Label>
      </View>
      <View style={styles.between}>
        <Label size={13}>{compactTokens(tokens)} tokens <Label muted size={12}>· {tokenCount(row.turns)} turns</Label></Label>
        <Label size={13} bold style={styles.numbers}>{usageMoney(row.costUsd)}</Label>
      </View>
      <View style={{ height: 4, borderRadius: 2, backgroundColor: c.chrome, overflow: "hidden" }}>
        <View style={{ height: 4, width: `${total > 0 ? Math.min(100, tokens / total * 100) : 0}%`, backgroundColor: c.outline }} />
      </View>
      <Label muted size={11}>Cache {percent(cache.rate)}{cache.rate !== null && !cache.complete ? " · reported input only" : ""}</Label>
    </Pressable>
    {expanded && <View style={{ marginHorizontal: 18, paddingVertical: 14, borderTopWidth: StyleSheet.hairlineWidth, borderColor: c.line, gap: 8 }}>
      <Detail label="Input tokens" value={tokenCount(row.input)} />
      <Detail label="Output tokens" value={tokenCount(row.output)} />
      <Detail label="Recorded cached input" value={cache.rate === null && !cache.cached ? "Unknown" : tokenCount(cache.cached)} />
      <Detail label="Recorded uncached input" value={cache.rate === null ? "Unknown" : tokenCount(cache.fresh)} />
      <Detail label="Cache-hit rate" value={percent(cache.rate)} />
      <Detail label="Input reporting coverage" value={percent(cache.coverage)} />
      {(row.unpriced ?? 0) > 0 && <Label muted size={11}>Cost not reported for {tokenCount(row.unpriced!)} turns.</Label>}
      {row.billableUsd != null && <Detail label="Billable" value={`${currency} ${row.billableUsd.toFixed(2)}`} />}
    </View>}
  </View>;
}
export function UsageBreakdown({ data, group }: { data: UsageSummary; group: UsageGrouping }) {
  return <View style={{ gap: 10 }}>
    {data.groups.length === 0 ? <Label muted>No activity in this period. Try another date range.</Label>
      : data.groups.map(row => <UsageBreakdownRow key={`${group}:${row.key}`} row={row} group={group}
        total={data.total.input + data.total.output} currency={data.billing?.currency ?? "USD"} />)}
  </View>;
}

const styles = StyleSheet.create({
  card: { borderRadius: 22, padding: 20, gap: 12 },
  numbers: { fontVariant: ["tabular-nums"], letterSpacing: -0.3 },
  metrics: { flexDirection: "row", flexWrap: "wrap", gap: 16 },
  between: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 12 },
  rule: { height: StyleSheet.hairlineWidth, marginVertical: 2 },
  footer: { paddingTop: 14, borderTopWidth: StyleSheet.hairlineWidth, flexDirection: "row", flexWrap: "wrap", justifyContent: "space-between", gap: 8 },
});
